core.test: save stdout, stderr and output as formated files
avocado-framework/avocado pull request #4187
Opened 2020-09-02 21:15 UTC by beraldoleal

When using raw handler, new lines are not preserved. This was the cause
of some issues. This closes #4167.

Signed-off-by: Beraldo Leal <bleal@redhat.com>

2020-09-02 21:31 UTC, willianrampazzo approved these changes

2020-09-02 21:38 UTC, clebergnu requested changes
Test failure:

```
======================================================================
FAIL: test_check_on_off (selftests.functional.test_output.OutputTest)
Checks that output will always be kept, but it will only make into
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builddir/build/BUILD/avocado-81.0/selftests/functional/test_output.py", line 299, in test_check_on_off
    '__STDOUT_CONTENT____STDOUT_DO_RECORD_CONTENT__')
AssertionError: '__STDOUT_CONTENT__\n__STDOUT_DO_RECORD_CONTENT__\n' != '__STDOUT_CONTENT____STDOUT_DO_RECORD_CONTENT__'
+ __STDOUT_CONTENT____STDOUT_DO_RECORD_CONTENT__- __STDOUT_CONTENT__
- __STDOUT_DO_RECORD_CONTENT__
```

2020-09-04 14:06 UTC, clebergnu commented
> so @clebergnu like I said, not sure here. Please double check if this is the right place to change this.

I'm looking into it now.

2020-09-08 18:37 UTC, clebergnu commented on selftests/functional/test_output.py
> +                                 '__STDOUT_CONTENT__\n__STDOUT_DO_RECORD_CONTENT__\n')
@beraldoleal I've doubled checked and the test does not write new lines, see: https://github.com/avocado-framework/avocado/blob/da13e14b0e42ad364bfb68b3a43cb3b637fa32aa/selftests/functional/test_output.py#L110

The question is now how/if the logging handler used to generate the `stdout` (and similar) files can receive the verbatim content (including newlines) to pass it along.  I'm still investigating that.

2020-09-09 15:02 UTC, clebergnu commented
Closing as #4213 was merged.

2020-09-09 15:02 UTC, closed without merging