function to get default route interface
avocado-framework/avocado pull request #4245
Opened 2020-09-21 06:09 UTC by smruti77

add get_default_route_interface() in host.py to get default
interface name.

Signed-off-by: bismurti bidhibrata pattajoshi <bbidhibr@in.ibm.com>

2020-09-21 14:11 UTC, beraldoleal requested changes
This is returning the first dev of the output list. Like I said on my previous comment if we have multiple defaults gateways this should return a list, not a single dev.

2020-09-21 16:43 UTC, pevogam commented
Has anyone thought about simply migrating the networking utilities from Avocado VT or methods/parts of them? It is quite possible that there is already a function like this there but I am just wondering.

2020-09-21 18:12 UTC, beraldoleal commented
> Has anyone thought about simply migrating the networking utilities from Avocado VT or methods/parts of them? It is quite possible that there is already a function like this there but I am just wondering.

That is nice to check, yes. But this `network/` module was completely redesigned a few months ago and its usage is a little simplified based only on two classes, so far: Host() and Interface().

2020-09-21 20:33 UTC, pevogam commented
> > Has anyone thought about simply migrating the networking utilities from Avocado VT or methods/parts of them? It is quite possible that there is already a function like this there but I am just wondering.
> 
> That is nice to check, yes. But this `network/` module was completely redesigned a few months ago and its usage is a little simplified based only on two classes, so far: Host() and Interface().

The current simplified implementation is another reason it would be good to migrate complete code from there instead of tens of PRs to follow that will gradually end up at the same target destination. But these are just ideas.

2020-09-22 11:43 UTC, beraldoleal commented on avocado/utils/network/hosts.py
> +        :return: interface name
Return a list of ifnae names.

2020-09-22 11:43 UTC, beraldoleal requested changes

2020-09-22 11:43 UTC, beraldoleal commented on avocado/utils/network/hosts.py
> +        """Get the default route interface
Get a list of default routes interfaces.

2020-09-22 11:44 UTC, beraldoleal commented
> > > Has anyone thought about simply migrating the networking utilities from Avocado VT or methods/parts of them? It is quite possible that there is already a function like this there but I am just wondering.
> > 
> > 
> > That is nice to check, yes. But this `network/` module was completely redesigned a few months ago and its usage is a little simplified based only on two classes, so far: Host() and Interface().
> 
> The current simplified implementation is another reason it would be good to migrate complete code from there instead of tens of PRs to follow that will gradually end up at the same target destination. But these are just ideas.

Yes, definitely I will check the methods implemented there.

2020-09-22 14:26 UTC, clebergnu commented
> Has anyone thought about simply migrating the networking utilities from Avocado VT or methods/parts of them? It is quite possible that there is already a function like this there but I am just wondering.

Hi @pevogam, this is the path that I suggested on this mailling list post:

https://www.redhat.com/archives/avocado-devel/2020-September/msg00006.html

It'd be nice to get feedback and some general consensus so we can start working towards it.

2020-09-22 15:28 UTC, pevogam commented
> > Has anyone thought about simply migrating the networking utilities from Avocado VT or methods/parts of them? It is quite possible that there is already a function like this there but I am just wondering.
> 
> Hi @pevogam, this is the path that I suggested on this mailling list post:
> 
> https://www.redhat.com/archives/avocado-devel/2020-September/msg00006.html
> 
> It'd be nice to get feedback and some general consensus so we can start working towards it.

Hi @clebergnu, I would love to respond as soon as I can but I am still catching up with the 82.0 release of our plugin (it follows your release schedule) and I am a bit behind there due to more time spent upstream and pushing through with additional PRs. If you have more time I would be glad to see some of your reactions on some of my individual troubles and blockades where I have pinged you explicitly.

I commented faster here since recently I saw a lot of tendency in developing duplicate functionality when it comes to networking that is already available in VT. I might be wrong though, I have only touched the `utils_net.py` on the surface.

2020-09-23 17:53 UTC, beraldoleal approved these changes
Thanks for the changes @smruti77 , this LGTM.

IMO, this is an improvement for what we have today in `utils_net.py` on avocado-vt side, since there is not returning a proper list in case multiple default routes.

2020-09-23 17:55 UTC, beraldoleal commented
@pevogam I share your concern and thanks for your quick input.

I will take care of migrating `utils_net.py` for the new place as suggested by @clebergnu on that thread. But I would like to follow a more OOP approach, like this one here.

2020-09-23 17:58 UTC, beraldoleal commented
/packit copr-build

2020-09-23 18:16 UTC, beraldoleal commented
@smruti77 just one small error with isort. Travis is complaining:

 (003/952) selftests/isort.sh:  FAIL (4.02 s)

2020-09-23 20:13 UTC, pevogam commented
Hi @beraldoleal,

> @pevogam I share your concern and thanks for your quick input.
> 
> I will take care of migrating `utils_net.py` for the new place as suggested by @clebergnu on that thread. But I would like to follow a more OOP approach, like this one here.

Following a more OOP approach or additional improvements don't contradict the argument of reuse. You could convert to OOP while migrating the code from there for instance. One way to confirm the development done here is superior to the development done there for instance would be to gradually deprecate their methods for the sake of the ones here and thus making sure by observation that all functional requirements on their side is already covered by avocado itself.

2020-09-23 21:08 UTC, beraldoleal commented
> Hi @beraldoleal,
> 
> > @pevogam I share your concern and thanks for your quick input.
> > I will take care of migrating `utils_net.py` for the new place as suggested by @clebergnu on that thread. But I would like to follow a more OOP approach, like this one here.
> 
> Following a more OOP approach or additional improvements don't contradict the argument of reuse. You could convert to OOP while migrating the code from there for instance. One way to confirm the development done here is superior to the development done there for instance would be to gradually deprecate their methods for the sake of the ones here and thus making sure by observation that all functional requirements on their side is already covered by avocado itself.

I think that I didn't express myself in the proper way. I agree with you, and we are talking about the same thing ;)


> In any case, I was just adding a minor note that could be of use to you and the rest of the avocado maintainers. I don't mean to spark a bigger conversation, merely to hint at more beneficial possibilities.

No worries. It was a valid point/reminder.

2020-09-24 04:39 UTC, smruti77 commented
> @smruti77 just one small error with isort. Travis is complaining:
> 
> (003/952) selftests/isort.sh: FAIL (4.02 s)
done

2020-09-24 10:26 UTC, beraldoleal commented
/packit copr-build

2020-09-25 11:24 UTC, merged