increase timeout value
avocado-framework/avocado pull request #4252
Opened 2020-09-25 06:25 UTC by vaishnavibhat

increasing the timeout value from 30s to 120s.
On changing the mtu value, few adapters take a longer time for the
operational state to come up. Setting this mtu value to max timeout
value.

Signed-off-by: Vaishnavi Bhat <vaishnavi@linux.vnet.ibm.com>

2020-09-25 07:25 UTC, abdhaleegit approved these changes
setting MTU command takes more time for different adapters and also at the remote system. so this increase time is needed to handle the same

2020-09-25 07:50 UTC, richtja approved these changes
LGTM

2020-09-25 11:00 UTC, beraldoleal requested changes
@vaishnavibhat @abdhaleegit I'm not sure here.

I did some tests with multiple NIC cards that I have access and all of them did the set inside the timeout. I think that is not fair with other users of this library to have them wait.

Do you have a list of cards that are taking so long? If this is just an exceptional case, then users of this library should change the values when using it. Like you said: " ... few adapters..."

Sorry for being so pokey here, but I just would like to make sure that this is not going to impact other users.

2020-09-25 12:09 UTC, willianrampazzo commented
> @vaishnavibhat @abdhaleegit I'm not sure here.
> 
> I did some tests with multiple NIC cards that I have access and all of them did the set inside the timeout. I think that is not fair with other users of this library to have them wait. Like you said: " ... few adapters..."
> 
> Do you have a list of cards that are taking so long? If this is just an exceptional case, then users of this library should change the values when using it.
> 
> Sorry for being so pokey here, but I just would like to make sure that this is not going to impact other users.

+1 for setting a longer timeout in the test side. If the majority of the interfaces take less than 30 seconds to be up, it makes more sense to do any customization in the test.

2020-09-25 12:22 UTC, beraldoleal commented
And just to be clear: I understand that by default, users will not have to wait because of how `wait_for()` will execute the code and exit before the timeout. But I'm talking about, if something went wrong, users will have to wait for too much to realize that.

So, unless I'm missing something, or some have a strong argument, I still think that it is a change that can be done on the caller.

2020-09-28 10:30 UTC, vaishnavibhat commented
Hi all, 

Thanks for the review comments. This is what I have in my logs when there is a MTU change: 

In a PASS case, I see the link up is happening with 30s. Interface has the flags assigned from "NO-CARRIER" to "UP","LOWER_UP" etc, within the timeout.

```ip link set eth1 mtu 5000
ip -4 -j address show eth1
[{"ifindex":2,"ifname":"eth1","flags":["NO-CARRIER","BROADCAST","MULTICAST","UP"],"mtu":1500,"qdisc":"mq","operstate":"DOWN","group":"default","txqlen":1000,"addr_info":[{"family":"inet","local":"192.168.10.1","prefixlen":24,"scope":"global","label":"eth1","valid_life_time":4294967295,"preferred_life_time":4294967295}]}]

ip -4 -j address show eth1
[{"ifindex":2,"ifname":"eth1","flags":["BROADCAST","MULTICAST","UP","LOWER_UP"],"mtu":1500,"qdisc":"mq","operstate":"UP","group":"default","txqlen":1000,"addr_info":[{"family":"inet","local":"192.168.10.1","prefixlen":24,"scope":"global","label":"eth1","valid_life_time"```


But when there is a delay, the flags are getting assigned to the interface but slower than 30 s and my tests are dropping to ERROR state because we are trying to use a flag that is not in the list.
```ip link set eth1 mtu 5000
ip -4 -j address show eth1
[{"ifindex":2,"ifname":"eth1","flags":["NO-CARRIER","BROADCAST","MULTICAST","UP"],"mtu":1500,"qdisc":"mq","operstate":"DOWN","group":"default","txqlen":1000,"addr_info":[{"family":"inet","local":"192.168.10.1","prefixlen":24,"scope":"global","label":"eth1","valid_life_time":4294967295,"preferred_life_time":4294967295}]}]

ip -4 -j address show eth1
[{"ifindex":2,"ifname":"eth1","flags":["BROADCAST","MULTICAST","UP"],"mtu":5000,"qdisc":"mq","operstate":"UP","group":"default","txqlen":1000,"addr_info":[{"family":"inet","local":"192.168.10.1","prefixlen":24,"scope":"global","label":"eth1","valid_life_time":4294967295,"preferred_life_time":4294967295}]}]


2020-09-18 21:48:34,522 stacktrace       L0045 ERROR|   File "/usr/local/lib/python3.6/site-packages/avocado_framework-82.0-py3.6.egg/avocado/utils/network/interfaces.py", line 165, in is_operational_link_up
2020-09-18 21:48:34,522 stacktrace       L0045 ERROR|     if self._get_interface_details().get('flags')[3] == 'LOWER_UP':
2020-09-18 21:48:34,522 stacktrace       L0045 ERROR| IndexError: list index out of range
2020-09-18 21:48:34,522 stacktrace       L0045 ERROR| 
2020-09-18 21:48:34,522 stacktrace       L0045 ERROR| During handling of the above exception, another exception occurred:
2020-09-18 21:48:34,522 stacktrace       L0045 ERROR| 
2020-09-18 21:48:34,522 stacktrace       L0045 ERROR| Traceback (most recent call last):
2020-09-18 21:48:34,522 stacktrace       L0045 ERROR|   File "/usr/local/lib/python3.6/site-packages/avocado_framework-82.0-py3.6.egg/avocado/core/test.py", line 747, in _run_avocado
2020-09-18 21:48:34,522 stacktrace       L0045 ERROR|     self.setUp()
2020-09-18 21:48:34,522 stacktrace       L0045 ERROR|   File "/root/tests/tests/avocado-misc-tests/io/net/tcpdump.py", line 84, in setUp
2020-09-18 21:48:34,522 stacktrace       L0045 ERROR|     if self.networkinterface.set_mtu(self.mtu) is not None:
2020-09-18 21:48:34,523 stacktrace       L0045 ERROR|   File "/usr/local/lib/python3.6/site-packages/avocado_framework-82.0-py3.6.egg/avocado/utils/network/interfaces.py", line 319, in set_mtu
2020-09-18 21:48:34,523 stacktrace       L0045 ERROR|     wait_for(self.is_link_up, timeout=timeout)
2020-09-18 21:48:34,523 stacktrace       L0045 ERROR|   File "/usr/local/lib/python3.6/site-packages/avocado_framework-82.0-py3.6.egg/avocado/utils/wait.py", line 34, in wait_for
2020-09-18 21:48:34,523 stacktrace       L0045 ERROR|     output = func(*args, **kwargs)
2020-09-18 21:48:34,523 stacktrace       L0045 ERROR|   File "/usr/local/lib/python3.6/site-packages/avocado_framework-82.0-py3.6.egg/avocado/utils/network/interfaces.py", line 177, in is_link_up
2020-09-18 21:48:34,523 stacktrace       L0045 ERROR|     return self.is_admin_link_up() and self.is_operational_link_up()
2020-09-18 21:48:34,523 stacktrace       L0045 ERROR|   File "/usr/local/lib/python3.6/site-packages/avocado_framework-82.0-py3.6.egg/avocado/utils/network/interfaces.py", line 168, in is_operational_link_up
2020-09-18 21:48:34,523 stacktrace       L0045 ERROR|     raise NWException("Could not get operational link state.")
2020-09-18 21:48:34,523 stacktrace       L0045 ERROR| avocado.utils.network.exceptions.NWException: Could not get operational link state.
2020-09-18 21:48:34,523 stacktrace       L0045 ERROR| ```

In a general scenario , this timing issue can be because of the adapter or because of the network connectivity. I think 30s is a good value in a ideal case but we should be able to wait a but longer than exiting the tests with ERROR.

2020-09-28 13:07 UTC, willianrampazzo commented
> Hi all,
> 
> Thanks for the review comments. This is what I have in my logs when there is a MTU change:
> 
> In a PASS case, I see the link up is happening with 30s. Interface has the flags assigned from "NO-CARRIER" to "UP","LOWER_UP" etc, within the timeout.
> 
> ```
> ip link set eth1 mtu 5000
> ip -4 -j address show eth1
> [{"ifindex":2,"ifname":"eth1","flags":["NO-CARRIER","BROADCAST","MULTICAST","UP"],"mtu":1500,"qdisc":"mq","operstate":"DOWN","group":"default","txqlen":1000,"addr_info":[{"family":"inet","local":"192.168.10.1","prefixlen":24,"scope":"global","label":"eth1","valid_life_time":4294967295,"preferred_life_time":4294967295}]}]
> 
> ip -4 -j address show eth1
> [{"ifindex":2,"ifname":"eth1","flags":["BROADCAST","MULTICAST","UP","LOWER_UP"],"mtu":1500,"qdisc":"mq","operstate":"UP","group":"default","txqlen":1000,"addr_info":[{"family":"inet","local":"192.168.10.1","prefixlen":24,"scope":"global","label":"eth1","valid_life_time"
> ```
> 
> But when there is a delay, the flags are getting assigned to the interface but slower than 30 s and my tests are dropping to ERROR state because we are trying to use a flag that is not in the list.
> 
> ```
> ip link set eth1 mtu 5000
> ip -4 -j address show eth1
> [{"ifindex":2,"ifname":"eth1","flags":["NO-CARRIER","BROADCAST","MULTICAST","UP"],"mtu":1500,"qdisc":"mq","operstate":"DOWN","group":"default","txqlen":1000,"addr_info":[{"family":"inet","local":"192.168.10.1","prefixlen":24,"scope":"global","label":"eth1","valid_life_time":4294967295,"preferred_life_time":4294967295}]}]
> 
> ip -4 -j address show eth1
> [{"ifindex":2,"ifname":"eth1","flags":["BROADCAST","MULTICAST","UP"],"mtu":5000,"qdisc":"mq","operstate":"UP","group":"default","txqlen":1000,"addr_info":[{"family":"inet","local":"192.168.10.1","prefixlen":24,"scope":"global","label":"eth1","valid_life_time":4294967295,"preferred_life_time":4294967295}]}]
> 
> 
> 2020-09-18 21:48:34,522 stacktrace       L0045 ERROR|   File "/usr/local/lib/python3.6/site-packages/avocado_framework-82.0-py3.6.egg/avocado/utils/network/interfaces.py", line 165, in is_operational_link_up
> 2020-09-18 21:48:34,522 stacktrace       L0045 ERROR|     if self._get_interface_details().get('flags')[3] == 'LOWER_UP':
> 2020-09-18 21:48:34,522 stacktrace       L0045 ERROR| IndexError: list index out of range
> 2020-09-18 21:48:34,522 stacktrace       L0045 ERROR| 
> 2020-09-18 21:48:34,522 stacktrace       L0045 ERROR| During handling of the above exception, another exception occurred:
> 2020-09-18 21:48:34,522 stacktrace       L0045 ERROR| 
> 2020-09-18 21:48:34,522 stacktrace       L0045 ERROR| Traceback (most recent call last):
> 2020-09-18 21:48:34,522 stacktrace       L0045 ERROR|   File "/usr/local/lib/python3.6/site-packages/avocado_framework-82.0-py3.6.egg/avocado/core/test.py", line 747, in _run_avocado
> 2020-09-18 21:48:34,522 stacktrace       L0045 ERROR|     self.setUp()
> 2020-09-18 21:48:34,522 stacktrace       L0045 ERROR|   File "/root/tests/tests/avocado-misc-tests/io/net/tcpdump.py", line 84, in setUp
> 2020-09-18 21:48:34,522 stacktrace       L0045 ERROR|     if self.networkinterface.set_mtu(self.mtu) is not None:
> 2020-09-18 21:48:34,523 stacktrace       L0045 ERROR|   File "/usr/local/lib/python3.6/site-packages/avocado_framework-82.0-py3.6.egg/avocado/utils/network/interfaces.py", line 319, in set_mtu
> 2020-09-18 21:48:34,523 stacktrace       L0045 ERROR|     wait_for(self.is_link_up, timeout=timeout)
> 2020-09-18 21:48:34,523 stacktrace       L0045 ERROR|   File "/usr/local/lib/python3.6/site-packages/avocado_framework-82.0-py3.6.egg/avocado/utils/wait.py", line 34, in wait_for
> 2020-09-18 21:48:34,523 stacktrace       L0045 ERROR|     output = func(*args, **kwargs)
> 2020-09-18 21:48:34,523 stacktrace       L0045 ERROR|   File "/usr/local/lib/python3.6/site-packages/avocado_framework-82.0-py3.6.egg/avocado/utils/network/interfaces.py", line 177, in is_link_up
> 2020-09-18 21:48:34,523 stacktrace       L0045 ERROR|     return self.is_admin_link_up() and self.is_operational_link_up()
> 2020-09-18 21:48:34,523 stacktrace       L0045 ERROR|   File "/usr/local/lib/python3.6/site-packages/avocado_framework-82.0-py3.6.egg/avocado/utils/network/interfaces.py", line 168, in is_operational_link_up
> 2020-09-18 21:48:34,523 stacktrace       L0045 ERROR|     raise NWException("Could not get operational link state.")
> 2020-09-18 21:48:34,523 stacktrace       L0045 ERROR| avocado.utils.network.exceptions.NWException: Could not get operational link state.
> 2020-09-18 21:48:34,523 stacktrace       L0045 ERROR|
> ```
> 
> In a general scenario , this timing issue can be because of the adapter or because of the network connectivity. I think 30s is a good value in a ideal case but we should be able to wait a but longer than exiting the tests with ERROR.

Have you changed the timeout value in your test to make it last 120 seconds as we mentioned previously? That way you will have the extended time you need. When the interface comes up into the 30 seconds range, your tests won't be impacted by the extended timeout.

2021-02-02 17:26 UTC, beraldoleal commented
I'm closing this because users could set timeout when using this method. @vaishnavibhat please, feel free to reopen if you have more comments to add.

2021-02-02 17:26 UTC, closed without merging