varianter_yaml_to_mux: Fix displaying empty/null value from yaml
avocado-framework/avocado pull request #4280
Opened 2020-10-27 12:52 UTC by harish-24

Patch fixes displaying empty/null value node provided from yaml

```
$ avocado variants -m nvdimm.yaml -c
Before patch:
Variant run-setup-disk_type-disk_scratch-disk_test-fs_type-fs_xfs-exclude-gen_exclude-b86f:    /run/setup/fs_type/fs_xfs/exclude, /run/setup/fs_type/fs_xfs/gen_exclude, /run/setup/disk_type/disk_test, /run/setup/disk_type/disk_scratch
    /run/setup/disk_type:type          => nvdimm
    /run/setup/fs_type/fs_xfs:fs       => xfs
    /run/setup/fs_type/fs_xfs:mkfs_opt => -b size=65536 -s size=4096 -m reflink=0
    /run/setup:mount_opt               => -o dax

After patch:
Variant run-setup-disk_type-fs_type-fs_xfs-8ca7:    /run/setup/fs_type/fs_xfs, /run/setup/disk_type
    /run/setup/disk_type:disk_scratch     => None
    /run/setup/disk_type:disk_test        => None
    /run/setup/disk_type:type             => nvdimm
    /run/setup/fs_type/fs_xfs:exclude     => None
    /run/setup/fs_type/fs_xfs:fs          => xfs
    /run/setup/fs_type/fs_xfs:gen_exclude => None
    /run/setup/fs_type/fs_xfs:mkfs_opt    => -b size=65536 -s size=4096 -m reflink=0
    /run/setup:mount_opt                  => -o dax

$ cat nvdimm.yaml
setup:
    mount_opt: '-o dax'
    fs_type: !mux
        fs_xfs:
            fs: 'xfs'
            mkfs_opt: '-b size=65536 -s size=4096 -m reflink=0'
            exclude: null
            gen_exclude: null
    disk_type:
        type: 'nvdimm'
        disk_test:
        disk_scratch:
```
Fixes: #4010

Signed-off-by: Harish <harish@linux.ibm.com>

2020-10-27 12:53 UTC, harish-24 commented
@willianrampazzo Please help reviewing this

2020-10-27 16:02 UTC, richtja requested changes
Hi @harish-24, thanks for this,  unfortunately the yaml_to_mux unit-tests are failing. Can you look at that? And also add your example as yaml_to_mux functional test. Thanks

2020-10-27 17:25 UTC, harish-24 commented
> Hi @harish-24, thanks for this, unfortunately the yaml_to_mux unit-tests are failing. Can you look at that? And also add your example as yaml_to_mux functional test. Thanks

Thanks @richtja. I was able to reproduce the failures, but unfortunately could not get the exact fail scenarios in each test because of the following error dumped in the log

```
2020-10-27 13:17:03,071 selector_events  L0054 DEBUG| Using selector: EpollSelector
2020-10-27 13:17:03,077 base_events      L1285 ERROR| Task exception was never retrieved
future: <Task finished coro=<StatusServer.serve_forever() done, defined at /usr/local/lib/python3.6/site-packages/avocado_framework-82.0-py3.6.egg/avocado/core/status/server.py:33> exception=AttributeError("'Server' object has no attribute 'serve_forever'",)>
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/avocado_framework-82.0-py3.6.egg/avocado/core/status/server.py", line 36, in serve_forever
    await self._server_task.serve_forever()
AttributeError: 'Server' object has no attribute 'serve_forever'
2020-10-27 13:17:03,635 job              L0609 INFO | Test results available in /home/harish/tests/results/job-2020-10-27T13.17-0fb3d18
```
Is there anything missing here or a known issue? Thanks in adavance.

2020-10-27 17:34 UTC, harish-24 commented
@richtja To add to that I am trying to understand here if the patch makes sense. If it does, I guess the selftests needs to be modified accordingly since an empty node with null/empty value is not treated as a MuxTree anymore?

2020-10-27 17:37 UTC, willianrampazzo commented
> > Hi @harish-24, thanks for this, unfortunately the yaml_to_mux unit-tests are failing. Can you look at that? And also add your example as yaml_to_mux functional test. Thanks
> 
> Thanks @richtja. I was able to reproduce the failures, but unfortunately could not get the exact fail scenarios in each test because of the following error dumped in the log
> 
> ```
> 2020-10-27 13:17:03,071 selector_events  L0054 DEBUG| Using selector: EpollSelector
> 2020-10-27 13:17:03,077 base_events      L1285 ERROR| Task exception was never retrieved
> future: <Task finished coro=<StatusServer.serve_forever() done, defined at /usr/local/lib/python3.6/site-packages/avocado_framework-82.0-py3.6.egg/avocado/core/status/server.py:33> exception=AttributeError("'Server' object has no attribute 'serve_forever'",)>
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.6/site-packages/avocado_framework-82.0-py3.6.egg/avocado/core/status/server.py", line 36, in serve_forever
>     await self._server_task.serve_forever()
> AttributeError: 'Server' object has no attribute 'serve_forever'
> 2020-10-27 13:17:03,635 job              L0609 INFO | Test results available in /home/harish/tests/results/job-2020-10-27T13.17-0fb3d18
> ```
> 
> Is there anything missing here or a known issue? Thanks in adavance.

Hi @harish-24, I ran the test on the current master and it ran without problems. What command are you using to run the tests?

2020-10-27 17:43 UTC, harish-24 commented
@willianrampazzo Same as what is being used in Travis
```
# avocado run --test-runner=nrunner --ignore-missing-references -- optional_plugins/varianter_yaml_to_mux/tests/test_unit.py:TestMuxTree.test_basic_functions 
JOB ID     : 6aec79e2790c0b38f1c651fd441f83d084b39c4e
JOB LOG    : /home/harish/tests/results/job-2020-10-27T13.05-6aec79e/job.log
 (1/1) optional_plugins/varianter_yaml_to_mux/tests/test_unit.py:TestMuxTree.test_basic_functions: STARTED
 (1/1) optional_plugins/varianter_yaml_to_mux/tests/test_unit.py:TestMuxTree.test_basic_functions: FAIL (0.01 s)
RESULTS    : PASS 0 | ERROR 0 | FAIL 1 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB TIME   : 1.61 s
```
but the log did not contain anything other than the failure

2020-10-27 17:53 UTC, willianrampazzo commented
> @willianrampazzo Same as what is being used in Travis
> 
> ```
> # avocado run --test-runner=nrunner --ignore-missing-references -- optional_plugins/varianter_yaml_to_mux/tests/test_unit.py:TestMuxTree.test_basic_functions 
> JOB ID     : 6aec79e2790c0b38f1c651fd441f83d084b39c4e
> JOB LOG    : /home/harish/tests/results/job-2020-10-27T13.05-6aec79e/job.log
>  (1/1) optional_plugins/varianter_yaml_to_mux/tests/test_unit.py:TestMuxTree.test_basic_functions: STARTED
>  (1/1) optional_plugins/varianter_yaml_to_mux/tests/test_unit.py:TestMuxTree.test_basic_functions: FAIL (0.01 s)
> RESULTS    : PASS 0 | ERROR 0 | FAIL 1 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
> JOB TIME   : 1.61 s
> ```
> 
> but the log did not contain anything other than the failure

Okay, seems this PR is affecting the nrunner.

2020-10-27 17:58 UTC, harish-24 commented
> > @willianrampazzo Same as what is being used in Travis
> > ```
> > # avocado run --test-runner=nrunner --ignore-missing-references -- optional_plugins/varianter_yaml_to_mux/tests/test_unit.py:TestMuxTree.test_basic_functions 
> > JOB ID     : 6aec79e2790c0b38f1c651fd441f83d084b39c4e
> > JOB LOG    : /home/harish/tests/results/job-2020-10-27T13.05-6aec79e/job.log
> >  (1/1) optional_plugins/varianter_yaml_to_mux/tests/test_unit.py:TestMuxTree.test_basic_functions: STARTED
> >  (1/1) optional_plugins/varianter_yaml_to_mux/tests/test_unit.py:TestMuxTree.test_basic_functions: FAIL (0.01 s)
> > RESULTS    : PASS 0 | ERROR 0 | FAIL 1 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
> > JOB TIME   : 1.61 s
> > ```
> > 
> > 
> > but the log did not contain anything other than the failure
> 
> Okay, seems this PR is affecting the nrunner.

If you are referring to the `AttributeError: 'Server' object has no attribute 'serve_forever'`, then it does not seem to be the case. I tried running the same on master without this patch, all unit tests passed but still the same call trace was observed in the log.

2020-10-27 18:05 UTC, willianrampazzo commented
> > > @willianrampazzo Same as what is being used in Travis
> > > ```
> > > # avocado run --test-runner=nrunner --ignore-missing-references -- optional_plugins/varianter_yaml_to_mux/tests/test_unit.py:TestMuxTree.test_basic_functions 
> > > JOB ID     : 6aec79e2790c0b38f1c651fd441f83d084b39c4e
> > > JOB LOG    : /home/harish/tests/results/job-2020-10-27T13.05-6aec79e/job.log
> > >  (1/1) optional_plugins/varianter_yaml_to_mux/tests/test_unit.py:TestMuxTree.test_basic_functions: STARTED
> > >  (1/1) optional_plugins/varianter_yaml_to_mux/tests/test_unit.py:TestMuxTree.test_basic_functions: FAIL (0.01 s)
> > > RESULTS    : PASS 0 | ERROR 0 | FAIL 1 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
> > > JOB TIME   : 1.61 s
> > > ```
> > > 
> > > 
> > > but the log did not contain anything other than the failure
> > 
> > 
> > Okay, seems this PR is affecting the nrunner.
> 
> If you are referring to the `AttributeError: 'Server' object has no attribute 'serve_forever'`, then it does not seem to be the case. I tried running the same on master without this patch, all unit tests passed but still the same call trace was observed in the log.

Weird, I don't have the exception in my logs when running the unit tests on the master.

2020-10-28 03:48 UTC, harish-24 commented
> @richtja To add to that I am trying to understand here if the patch makes sense. If it does, I guess the selftests needs to be modified accordingly since an empty node with null/empty value is not treated as a MuxTree anymore?
> 
> More details on the requirement is here: #4010

@willianrampazzo @richtja Please share your thoughts on this, Thanks.

2020-10-28 10:52 UTC, richtja commented
> > > > @willianrampazzo Same as what is being used in Travis
> > > > ```
> > > > # avocado run --test-runner=nrunner --ignore-missing-references -- optional_plugins/varianter_yaml_to_mux/tests/test_unit.py:TestMuxTree.test_basic_functions 
> > > > JOB ID     : 6aec79e2790c0b38f1c651fd441f83d084b39c4e
> > > > JOB LOG    : /home/harish/tests/results/job-2020-10-27T13.05-6aec79e/job.log
> > > >  (1/1) optional_plugins/varianter_yaml_to_mux/tests/test_unit.py:TestMuxTree.test_basic_functions: STARTED
> > > >  (1/1) optional_plugins/varianter_yaml_to_mux/tests/test_unit.py:TestMuxTree.test_basic_functions: FAIL (0.01 s)
> > > > RESULTS    : PASS 0 | ERROR 0 | FAIL 1 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
> > > > JOB TIME   : 1.61 s
> > > > ```
> > > > 
> > > > 
> > > > but the log did not contain anything other than the failure
> > > 
> > > 
> > > Okay, seems this PR is affecting the nrunner.
> > 
> > 
> > If you are referring to the `AttributeError: 'Server' object has no attribute 'serve_forever'`, then it does not seem to be the case. I tried running the same on master without this patch, all unit tests passed but still the same call trace was observed in the log.
> 
> Weird, I don't have the exception in my logs when running the unit tests on the master.

I think we have some problems with the logging system. Because on my system no of the test-specific logs are created.

2020-10-28 10:58 UTC, richtja commented
> > @richtja To add to that I am trying to understand here if the patch makes sense. If it does, I guess the selftests needs to be modified accordingly since an empty node with null/empty value is not treated as a MuxTree anymore?
> > More details on the requirement is here: #4010
> 
> @willianrampazzo @richtja Please share your thoughts on this, Thanks.

I think that the use-case from #4010 makes sense and we should do it. But we should distinguish two cases when the value is empty and when the value is null. Because that lets you stay with present behavior and adds a possibility of None value.

2020-10-28 12:25 UTC, harish-24 commented
> > > @richtja To add to that I am trying to understand here if the patch makes sense. If it does, I guess the selftests needs to be modified accordingly since an empty node with null/empty value is not treated as a MuxTree anymore?
> > > More details on the requirement is here: #4010
> > 
> > 
> > @willianrampazzo @richtja Please share your thoughts on this, Thanks.
> 
> I think that the use-case from #4010 makes sense and we should do it. But we should distinguish two cases when the value is empty and when the value is null. Because that lets you stay with present behavior and adds a possibility of None value.

@richtja Thanks for your comments. This is the only probable solution I could come up with here. This is where we lose the value of `None` from a provided input.
In the current implementation what we have before the `None` check (removed in this patch) is
```
def _mapping_to_tree_loader(loader, node, looks_like_node=False):
    """Maps yaml mapping tag to TreeNode structure"""
...
...
    objects = ListOfNodeObjects()
    for name, values in _value:
        print(name, values)                   -------------------------------------------------> here
        if isinstance(values, ListOfNodeObjects):   # New node from list
            objects.append(_tree_node_from_values(loader.path, name,
                                                  values, loader.using))
```
which prints
```
fs_ext4 OrderedDict([('fs', 'ext4'), ('mkfs_opt', '-b 65536')])
fs_xfs OrderedDict([('fs', 'xfs'), ('mkfs_opt', '-b size=65536 -s size=4096 -m reflink=0'), ('exclude', None), ('gen_exclude', None)])
```
corresponding yaml:
```
    fs_type: !mux
        fs_ext4:
            fs: 'ext4'
            mkfs_opt: '-b 65536'
        fs_xfs:
            fs: 'xfs'
            mkfs_opt: '-b size=65536 -s size=4096 -m reflink=0'
            exclude: null
            gen_exclude:
```
This means there is no specific way we can differentiate between an `empty` (gen_exclude) and a `null` (exclude) node. So with the current implementation an empty node like `gen_exclude` in this case will be treated the same as a node with `null` (i.e. `exclude`). 

Besides that, I am also trying to understand the need to differentiate a empty (leaf) node as a `MuxTreeNode` here?  Because of that, adding the empty nodes to the paths here does not make sense either.
```
$ avocado variants -m nvdimm.yaml -c
Variant run-setup-disk_type-disk_scratch-disk_test-fs_type-fs_xfs-exclude-gen_exclude-b86f:    /run/setup/fs_type/fs_xfs/exclude, /run/setup/fs_type/fs_xfs/gen_exclude
...
...
```

If there is anything which I failed to consider here, kindly let me know.

2020-10-29 10:00 UTC, richtja commented
> This means there is no specific way we can differentiate between an `empty` (gen_exclude) and a `null` (exclude) node. So with the current implementation an empty node like `gen_exclude` in this case will be treated the same as a node with `null` (i.e. `exclude`).
> 

Thanks for the explanation, I can see that we can't differentiate between an `empty` (gen_exclude) and a `null` (exclude) node. 


> Besides that, I am also trying to understand the need to differentiate a empty (leaf) node as a `MuxTreeNode` here? Because of that, adding the empty nodes to the paths here does not make sense either.
> 
> ```
> $ avocado variants -m nvdimm.yaml -c
> Variant run-setup-disk_type-disk_scratch-disk_test-fs_type-fs_xfs-exclude-gen_exclude-b86f:    /run/setup/fs_type/fs_xfs/exclude, /run/setup/fs_type/fs_xfs/gen_exclude
> ...
> ...
> ```
> 
> If there is anything which I failed to consider here, kindly let me know.

Unfortunately, we need to use empty node as a `MuxTreeNode` because of default values. Here is an simplified example from tests:
```
cpu: !mux 
   intel: 
       cpu_CFLAGS: '-march=core2' 
disk: !mux 
   disk_type: 'virtio' 
   scsi: 
       disk_type: 'scsi' 
   virtio_1: 
   virtio_2: 
```
Here if don't have empty node as a `MuxTreeNode, we wouldn't have variants with `virtio_1` and `virtio_2` and that is a problem.
Actually I don't know if this issue can be solved with yaml_to_mux `null` values and maybe the best solution will be using 'null' as a string like @willianrampazzo proposed in #4010 and inside yaml_to_mux rewrite 'null' strings to `None`. @harish-24 and @willianrampazzo what do you think?

2020-11-02 04:24 UTC, harish-24 commented
> Actually I don't know if this issue can be solved with yaml_to_mux `null` values and maybe the best solution will be using `null` as a string like @willianrampazzo proposed in #4010 and inside yaml_to_mux rewrite `null` strings to `None`. @harish-24 and @willianrampazzo what do you think?

@richtja Thanks for explaining. If this is a limitation from avocado end, we should probably change the last section of docstring to adhere to using `null` as a string.

https://avocado-framework.readthedocs.io/en/82.0/plugins/optional/varianter_yaml_to_mux.html#keys-and-values states
```
Note that due to different usage of key and values in environment we disabled the automatic value conversion for keys while keeping it enabled for values. This means that the value can be of any YAML supported value, eg. bool, None, list or custom type, while the key is always string.
```

2020-11-04 16:55 UTC, richtja commented
> > Actually I don't know if this issue can be solved with yaml_to_mux `null` values and maybe the best solution will be using `null` as a string like @willianrampazzo proposed in #4010 and inside yaml_to_mux rewrite `null` strings to `None`. @harish-24 and @willianrampazzo what do you think?
> 
> @richtja Thanks for explaining. If this is a limitation from avocado end, we should probably change the last section of docstring to adhere to using `null` as a string.
> 
> https://avocado-framework.readthedocs.io/en/82.0/plugins/optional/varianter_yaml_to_mux.html#keys-and-values states
> 
> ```
> Note that due to different usage of key and values in environment we disabled the automatic value conversion for keys while keeping it enabled for values. This means that the value can be of any YAML supported value, eg. bool, None, list or custom type, while the key is always string.
> ```
@harish-24 you are absolutely right. I created PR #4288 about this, please look at it. Thanks

2020-11-19 09:29 UTC, richtja commented
After the discussion and PR #4288, I am closing this. The issue #4010 will be still open as `low-hanging-fruit`

2020-11-19 09:29 UTC, closed without merging