Nrunner support to timeout class attribute
avocado-framework/avocado pull request #4287
Opened 2020-11-04 15:59 UTC by richtja

It adds support to the timeout class attribute for avocado instrumented tests in nrunner.

Reference:#4257
Signed-off-by: Jan Richter <jarichte@redhat.com>

2020-11-04 18:10 UTC, beraldoleal requested changes

2020-11-04 18:10 UTC, beraldoleal commented on avocado/core/nrunner_avocado_instrumented.py
> +        timeout = float(timeout or self.DEFAULT_TIMEOUT)
```python 
timeout = float(early_status.get('timeout', self.DEFAULT_TIMEOUT))
```

2020-11-05 14:26 UTC, richtja commented
@beraldoleal Thanks for your comment, I will push the change here.

2020-11-05 18:29 UTC, beraldoleal commented on avocado/core/nrunner_avocado_instrumented.py
> +    DEFAULT_TIMEOUT = 86400
How could we make this a custom setting by the users? This is something that I'm trying to do for the "skip exit codes".

2020-11-05 18:29 UTC, beraldoleal approved these changes

2020-11-05 19:12 UTC, willianrampazzo approved these changes
Tested and it works as expected.

2020-11-11 19:41 UTC, merged