Enable Python3 checker messages for dict.iter*()
avocado-framework/avocado pull request #4411
Opened 2021-02-10 03:03 UTC by tiagohonorato

Dict methods iteritems(), iterkeys() and itervalues() are longer supported
in Python 3. The check was disabled for some lines as AvocadoParam,
AvocadoParams and ValueDict classes define a method called iteritems()
that triggers the warning.

Related to #3466

Signed-off-by: Tiago Honorato <tiagohonorato1@gmail.com>

2021-02-11 10:42 UTC, richtja requested changes
Hi @tiagohonorato LGTM, just can you please resolve the conflicts which formed after the merge of your last PR #4405

2021-02-11 12:18 UTC, tiagohonorato commented
Hi @richtja, thanks for pointing that out. I will resolve the conflicts.

2021-02-11 13:52 UTC, richtja approved these changes
LGTM, thanks

2021-02-19 20:59 UTC, willianrampazzo reviewed
This PR fixes 3 places and adds local disables in 8 places. I'm wondering if it is worth enabling the check globally without fixing most of the places we have problems with now.

2021-02-22 04:04 UTC, tiagohonorato commented
Hi @willianrampazzo, the check was disabled in some places because I see those as false positives. To issue the warning, Pylint seems to just check whether methods named ``iterkeys()``, ``itervalues()`` and ``iteritems()`` are called, not taking the instance in consideration, in other words, if it is a ``dict`` (I will take a closer look at Pylint's codebase and open an issue there if it is confirmed). Consequently, if we define a method named ``iterkeys()``, ``itervalues()`` or ``iteritems()`` it will trigger the error when called, even though we are not referring to an instance of ``dict``, but to, for example, an instance of ``AvocadoParam``.

On the other hand, I see your point and it might be useful to change these names that conflict with ``dict.iter*``methods to avoid confusion when the check is enabled, specially for new code that uses ``AvocadoParam`` and ``AvocadoParams``. Maybe change these methods to something like ``iter_items()``, what do you think?

2021-02-22 04:09 UTC, tiagohonorato commented on optional_plugins/varianter_yaml_to_mux/avocado_varianter_yaml_to_mux/mux.py
> +        return self.iteritems()  # pylint: disable=W1620
By the way, after reviewing the modifications after @willianrampazzo's comment, we might me able to remove this method entirety, as ``ValueDict`` inherits from ``dict`` and the return from ``dict.items`` is already an iterator.

2021-02-22 09:09 UTC, richtja commented
> Hi @willianrampazzo, the check was disabled in some places because I see those as false positives. To issue the warning, Pylint seems to just check whether methods named `iterkeys()`, `itervalues()` and `iteritems()` are called, not taking the instance in consideration, in other words, if it is a `dict` (I will take a closer look at Pylint's codebase and open an issue there if it is confirmed). Consequently, if we define a method named `iterkeys()`, `itervalues()` or `iteritems()` it will trigger the error when called, even though we are not referring to an instance of `dict`, but to, for example, an instance of `AvocadoParam`.
> 
> On the other hand, I see your point and it might be useful to change these names that conflict with `dict.iter*`methods to avoid confusion when the check is enabled, specially for new code that uses `AvocadoParam` and `AvocadoParams`. Maybe change these methods to something like `iter_items()`, what do you think?

@willianrampazzo, @tiagohonorato about this problem I already opened discussion #4414, where we can find out the best approach.

2021-02-22 13:38 UTC, willianrampazzo commented
> > Hi @willianrampazzo, the check was disabled in some places because I see those as false positives. To issue the warning, Pylint seems to just check whether methods named `iterkeys()`, `itervalues()` and `iteritems()` are called, not taking the instance in consideration, in other words, if it is a `dict` (I will take a closer look at Pylint's codebase and open an issue there if it is confirmed). Consequently, if we define a method named `iterkeys()`, `itervalues()` or `iteritems()` it will trigger the error when called, even though we are not referring to an instance of `dict`, but to, for example, an instance of `AvocadoParam`.
> > On the other hand, I see your point and it might be useful to change these names that conflict with `dict.iter*`methods to avoid confusion when the check is enabled, specially for new code that uses `AvocadoParam` and `AvocadoParams`. Maybe change these methods to something like `iter_items()`, what do you think?
> 
> @willianrampazzo, @tiagohonorato about this problem I already opened discussion #4414, where we can decide the best approach.

Thanks, @richtja!

2021-02-22 13:39 UTC, willianrampazzo commented
> Hi @willianrampazzo, the check was disabled in some places because I see those as false positives. To issue the warning, Pylint seems to just check whether methods named `iterkeys()`, `itervalues()` and `iteritems()` are called, not taking the instance in consideration, in other words, if it is a `dict` (I will take a closer look at Pylint's codebase and open an issue there if it is confirmed). Consequently, if we define a method named `iterkeys()`, `itervalues()` or `iteritems()` it will trigger the error when called, even though we are not referring to an instance of `dict`, but to, for example, an instance of `AvocadoParam`.
> 
> On the other hand, I see your point and it might be useful to change these names that conflict with `dict.iter*`methods to avoid confusion when the check is enabled, specially for new code that uses `AvocadoParam` and `AvocadoParams`. Maybe change these methods to something like `iter_items()`, what do you think?

I see your point and I agree it makes sense.

2021-02-22 13:39 UTC, willianrampazzo approved these changes

2021-03-01 16:49 UTC, beraldoleal requested changes
@tiagohonorato, thanks for this. LGTM, but my only suggestion is to rebase this on top of the master and remove the "merge" commit.

2021-03-02 02:56 UTC, tiagohonorato commented
@beraldoleal, sure!

2021-03-02 03:25 UTC, tiagohonorato commented
I decided to keep ``ValueDict.iteritems()`` and ``ValueDict.items()`` here, as that may need further discussion and keeping those shouldn't cause any problems.

2021-03-02 14:09 UTC, beraldoleal approved these changes

2021-03-02 14:10 UTC, merged