Log information when running tests
avocado-framework/avocado pull request #4530
Opened 2021-04-14 15:22 UTC by richtja

Adds the test start and finish information in the `job.log`. So, if a
test "1-foo" passes, that should be easy to spot in the job.log file.

Reference: #4366
Signed-off-by: Jan Richter <jarichte@redhat.com>

2021-04-14 17:41 UTC, beraldoleal requested changes
Hi @richtja , thanks for this. LGTM, just a few small comments.

2021-04-14 17:41 UTC, beraldoleal commented on avocado/plugins/testlogs.py
> +        return name
What about?
```python
name = state.get('name')
if name is None:
    return "<unknown>"
return name.name + name.str_variant
```

2021-04-14 17:41 UTC, beraldoleal commented on avocado/plugins/testlogs.py
> +    description = "Test logs for Job"
Maybe be nice to document here and/or any other place that this is specific for nrunner.

2021-04-15 11:26 UTC, richtja commented
Hi @beraldoleal  thanks for your review, I processed your comments and force pushed the changes. I also appended the tests.

2021-04-15 12:28 UTC, beraldoleal approved these changes
LGTM, Thank you.

2021-04-16 07:14 UTC, merged