Config variable for resolvers
avocado-framework/avocado pull request #4713
Opened 2021-06-23 09:47 UTC by richtja

The resolvers don't have access to the config variable, and they are
using `settings.as_dict()`. Unfortunately, this method returns only
config from command line and config files. When the configuration is
created by Job API, the `settings.as_dict()` doesn't respect that. This
leads to the incompatibility between resolvers config and suite config
created by `TestSuite.from_config()` in Job API.

This problem was hidden because avocado default resolvers don't need
config for resolving references and `TestSuite.from_config()` rewrites
the runnables config created by resolvers.

It is not such a big problem for avocado default resolvers, but it is a
problem for vt resolver which is using config in resolving process.

Signed-off-by: Jan Richter <jarichte@redhat.com>

2021-06-23 12:18 UTC, beraldoleal reviewed
Hi @richtja, `settings.as_dict()` should be respecting custom configs as well. If this is not happening so maybe we have a problem. I need to take a closer look here and I might need some extra time.

Do you have any small reproducible on this?

2021-06-23 13:14 UTC, richtja commented
@beraldoleal the problem is quite tricky and is hidden inside resolver. So I edited the magic runner for revealing the problem. You can get it from [here](https://github.com/richtja/avocado/commit/fa5410c9a38baf1f9bc509b826423313f5282bdd).

2021-06-25 21:21 UTC, clebergnu commented
> Hi @richtja, `settings.as_dict()` should be respecting custom configs as well. If this is not happening so maybe we have a problem. I need to take a closer look here and I might need some extra time.
>

Hi @beraldoleal, would `settings.as_dict()` include the job-level or suite-level configuration?  I'm confused as to how it could.
 
> Do you have any small reproducible on this?

2021-06-25 21:42 UTC, clebergnu requested changes
Hi @richtja,

I understand the need to access the configuration in the resolvers, but I don't think it's necessary to change the `resolve()` and `discover()` signatures.  As an interface that is used by many plugins, this would introduce the need to handle compatibility with both versions.

It should be possible to pass the configuration automatically at the class initialization time.  Examples of that include the Spawner plugins, which have access to `self.config` "transparently" without the need to have them passed in methods such as `spawn_task()`.

Please let me know if you think my comment makes sense.

2021-06-28 13:28 UTC, richtja commented
> It should be possible to pass the configuration automatically at the class initialization time. Examples of that include the Spawner plugins, which have access to `self.config` "transparently" without the need to have them passed in methods such as `spawn_task()`.

Hi @clebergnu,  I think we can't use the same practice as `Spawner plugins` because they are getting the config via `settings.as_dict()` and this method doesn't respect suite specific configuration. And that is the problem which this PR is trying to solve.

2021-06-29 09:48 UTC, richtja commented
@clebergnu thanks for your comments, I created v2 #4746

2021-06-29 09:48 UTC, closed without merging