nrunner: bind tasks to their rightful jobs
avocado-framework/avocado pull request #4864
Opened 2021-08-18 03:03 UTC by clebergnu

This extends the nrunner Task, so that it can be set and report its rightful job.  This will help to identify erroneous situations where jobs receive information from other jobs tasks.

This can help, for instance, when a job runs another job as a test, or when some other bad actor tries to inject such data.

This is related to https://github.com/avocado-framework/avocado/issues/4308

2021-08-18 10:00 UTC, richtja requested changes
Hi @clebergnu thank you for this, I left a few small comments for you.

2021-08-18 13:28 UTC, clebergnu commented on avocado/core/nrunner.py
> +                   'results of the job' % TASK_DEFAULT_CATEGORY)}),
Well, the other components don't make that judgement based on a boolean, but whether a task is of category "test" or something else.  I thought it'd make sense to keep it symmetric here.

2021-08-18 13:30 UTC, clebergnu commented on avocado/core/status/repo.py
> +        if job_id != self.job_id:
I decided to *start* with logging, without discarding messages to help in further debugging... But  I think you're right: I can log the entire message and not process it.

2021-08-18 13:46 UTC, richtja commented on avocado/core/nrunner.py
> +                   'results of the job' % TASK_DEFAULT_CATEGORY)}),
Yes, I am not proposing to make it a boolean value, I just think that the help message can be better. Something like 'The category for tasks. Only the "%s" (the default) category will be included in the results of the job, the others are not used for tests'. But maybe it's just my personal feeling.

2021-08-18 22:10 UTC, beraldoleal approved these changes
Except from the @richtja comments, this LGTM.

2021-08-19 00:43 UTC, clebergnu commented on avocado/core/nrunner.py
> +                   'results of the job' % TASK_DEFAULT_CATEGORY)}),
> Yes, I am not proposing to make it a boolean value, I just think that the help message can be better. Something like 'The category for tasks. Only the "%s" (the default) category will be included in the results of the job, the others are not used for tests'. But maybe it's just my personal feeling.

I've changed the text for v2, the resulting help message being: "The category for tasks. Only tasks with category set to "test" (the default) will be included in the test results of its parent job. Other categories may be used for purposes that do include test results such as requirements resolution tasks'"

2021-08-19 01:06 UTC, clebergnu commented
Closing in favor of #4872

2021-08-19 01:06 UTC, closed without merging