CI: deployment of Avocado via different methods [v2]
avocado-framework/avocado pull request #4868
Opened 2021-08-18 16:18 UTC by ana

This is a v2 of https://github.com/avocado-framework/avocado/pull/4849
Changes:
* enabled all the methods with avocado_vt, so the 6 combinations are run now
* improve the pipeline to use directly the container support provided by GitHub Actions
* Update the list of repositories used, notably for the official method.
* Some minor changes following discussion in the v1

The current pipeline can be browsed at https://github.com/ana/avocado2/runs/3363033419

The job `Ansible (method=official avocado_vt=true)` doesn't work because the packages of avocado-vt haven't been updated yet. I added the missing releases at https://copr.fedorainfracloud.org/coprs/g/avocado/avocado-vt-latest/ and right now it works when `method=copr`, but I don't know if it'll update eventually the module avocado-vt or there is something else to do.

2021-08-18 17:32 UTC, willianrampazzo approved these changes
Nice work! So far, looks good to me.

2021-08-18 17:49 UTC, clebergnu commented on selftests/deployment/roles/avocado/tasks/rpm/examples.yml
> +      - python-avocado-examples
I'm not sure why we have different package names on upstream (thus on COPR) and on the official Fedora packages... I believe this is not intentional.

Anyway, your change is correct, but it'd be nice to look into that too.

2021-08-18 18:03 UTC, clebergnu requested changes
Hi @ana, this looks great, but the `method=official avocado_vt=true` job is failing.  I reproduced it and it seems to be caused by the fact that the package name on the Fedora module is `python3-avocado-vt`.

2021-08-18 18:26 UTC, ana commented
> Hi @ana, this looks great, but the `method=official avocado_vt=true` job is failing. I reproduced it and it seems to be caused by the fact that the package name on the Fedora module is `python3-avocado-vt`.

The `python3-avocado-vt` available right now has an older version `82.0-2.module_f34` see at http://fedora.mirror.iweb.com/linux/updates/testing/34/Modular/x86_64/Packages/p/ 

As I asked in the intro of the PR, I'd like to know how I can to push for a rebuild of this. Then it might happen the package is indeed named like that, but for what I saw in the current spec file I'm expecting `python3-avocado-plugins-vt`

2021-08-18 21:24 UTC, beraldoleal approved these changes
Except the @clebergnu's comments. LGTM, thanks.

2021-08-19 10:55 UTC, ana commented
> The `python3-avocado-vt` available right now has an older version `82.0-2.module_f34` see at http://fedora.mirror.iweb.com/linux/updates/testing/34/Modular/x86_64/Packages/p/

Or:

```
dnf module info avocado-vt 
Última comprobación de caducidad de metadatos hecha hace 0:26:43, el Thu Aug 19 12:26:51 2021.
Name             : avocado-vt
Stream           : 82lts
Version          : 3420210223014346
Context          : 035be0ad
Architecture     : x86_64
Profiles         : default
Default profiles : 
Repo             : fedora-modular
Summary          : Avocado Virt Test Plugin
Description      : Avocado Virt Test is a plugin that lets you execute virt-tests with all the avocado convenience features, such as HTML report, Xunit output, among others. This is the 'latest' rolling stream that tracks with the most recent upstream release.
Requires         : avocado:[82lts]
                 : platform:[f34]
Artifacts        : avocado-vt-0:82.0-2.module_f34+11469+a0cf4ea8.src
                 : python3-avocado-vt-0:82.0-2.module_f34+11469+a0cf4ea8.noarch

Name             : avocado-vt
Stream           : 82lts
Version          : 3420210223014346
Context          : 035be0ad
Architecture     : x86_64
Profiles         : default
Default profiles : 
Repo             : updates-modular
Summary          : Avocado Virt Test Plugin
Description      : Avocado Virt Test is a plugin that lets you execute virt-tests with all the avocado convenience features, such as HTML report, Xunit output, among others. This is the 'latest' rolling stream that tracks with the most recent upstream release.
Requires         : avocado:[82lts]
                 : platform:[f34]
Artifacts        : avocado-vt-0:82.0-2.module_f34+11469+a0cf4ea8.src
                 : python3-avocado-vt-0:82.0-2.module_f34+11469+a0cf4ea8.noarch

Name             : avocado-vt
Stream           : latest [e] [a]
Version          : 3420210201190451
Context          : 86fec018
Architecture     : x86_64
Profiles         : default
Default profiles : 
Repo             : fedora-modular
Summary          : Avocado Virt Test Plugin
Description      : Avocado Virt Test is a plugin that lets you execute virt-tests with all the avocado convenience features, such as HTML report, Xunit output, among others. This is the 'latest' rolling stream that tracks with the most recent upstream release.
Requires         : avocado:[latest]
                 : platform:[f34]
Artifacts        : avocado-vt-0:82.0-2.module_f34+11147+a70c8976.src
                 : python3-avocado-vt-0:82.0-2.module_f34+11147+a70c8976.noarch

Name             : avocado-vt
Stream           : latest [e] [a]
Version          : 3420210201190451
Context          : 86fec018
Architecture     : x86_64
Profiles         : default
Default profiles : 
Repo             : updates-modular
Summary          : Avocado Virt Test Plugin
Description      : Avocado Virt Test is a plugin that lets you execute virt-tests with all the avocado convenience features, such as HTML report, Xunit output, among others. This is the 'latest' rolling stream that tracks with the most recent upstream release.
Requires         : avocado:[latest]
                 : platform:[f34]
Artifacts        : avocado-vt-0:82.0-2.module_f34+11147+a70c8976.src
                 : python3-avocado-vt-0:82.0-2.module_f34+11147+a70c8976.noarch

```

I'm trying to find out how to update this.

2021-09-02 23:52 UTC, clebergnu approved these changes
LGTM, thanks!

2021-09-02 23:54 UTC, merged