Ansible deployment updates after switching to nrunner
avocado-framework/avocado pull request #4937
Opened 2021-09-07 14:05 UTC by ana

Two updates:
* we have different names for the avocado-vt package: python3-avocado-plugins-vt in copr and python3-avocado-vt in "official". Handle this while we it solved.
* The installation via pip was failing with avocado-vt with the error: 
`Avocado job failed: JobError: Could not find runners for runnable(s) of kind(s): dry-run` I applied the same workaround found here with cirrus https://github.com/avocado-framework/avocado-vt/pull/3204
* For some unknown reason (to me), the boot job now is named `io-github-autotest-qemu.boot` instead of `migrate.default.tcp.default`

These changes are working when I test locally but when running in github actions, I get two methods (pip and copr) failing in one of the avocado-vt tests ( boot and migrate execution), see:
https://github.com/ana/avocado/runs/3534440269

2021-09-07 14:22 UTC, clebergnu commented on selftests/deployment/roles/avocado/tasks/rpm/plugins.yml
> +    name: python3-avocado-vt
ACK.  I wonder why the naming was not followed.  Best bet is Fedora reviewers asked nicely, and package owner followed suit.

2021-09-07 14:23 UTC, clebergnu commented on selftests/deployment/roles/tests/tasks/main.yml
> +  shell: "PATH={{ temporary_dir.path | default('/usr') }}/bin/:$PATH {{ temporary_dir.path | default('/usr') }}/bin/avocado run --vt-extra-params='nettype=user' -- boot io-github-autotest-qemu.boot"
You're changing the tests here: dropping migrate and running boot twice.

2021-09-07 18:58 UTC, ana commented
@clebergnu I have done an update as discussed today. Now the error with `method=pip ` and `method=copr` when running the last step (Avocado-VT test 5/5 - boot and migrate execution)  is 
`Could not resolve references: type_specific.io-github-autotest-qemu.migrate.default.tcp.default`
This is with avocado `0.91`

It's working with `method=official` because it's installing avocado and avocado-vt **0.90**.

2021-09-13 14:00 UTC, clebergnu requested changes
Hi @ana, the change in test names is not really needed or wanted here.  With the Avocado-VT bug for multiple resolutions fixed, this should be kept as before.

2021-09-13 16:18 UTC, clebergnu approved these changes
@ana, sorry for the confusion.

My comment about *not changing* the test names, was based on this earlier version you proposed:

```
shell: "PATH={{ temporary_dir.path | default('/usr') }}/bin/:$PATH {{ temporary_dir.path | default('/usr') }}/bin/avocado run --vt-extra-params='nettype=user' -- boot io-github-autotest-qemu.boot"
```

^ There, you essentially ran the same test (boot) twice, with different names.  It may have felt right because of the Avocado-VT bug fixed in https://github.com/avocado-framework/avocado-vt/pull/3211, which prevented *different* test names from being resolved.

Now, your change of names is *optional*, but correct!  Thanks a lot and sorry for the noise.

2021-09-13 16:38 UTC, willianrampazzo approved these changes

2021-09-13 18:52 UTC, beraldoleal approved these changes
LGTM, thanks.

2021-09-13 21:17 UTC, merged