runnable: introduce custom formmat f-strings
avocado-framework/avocado pull request #5141
Opened 2021-11-17 14:14 UTC by beraldoleal

With this experimental change, we are enabling users to set custom
identifiers for the runnables/tests. By default we are still using {uri}
as identifier but any custom f-string using uri, args and/or kwargs can
be used. For now we have a global settings for all runners, since we
have the ability to create custom suites. However future improvements
can be added here.

Fixes #4980.

Signed-off-by: Beraldo Leal <bleal@redhat.com>

2021-11-18 10:41 UTC, richtja approved these changes
LGTM, thanks

2021-11-22 14:13 UTC, clebergnu commented on avocado/core/__init__.py
> +                         key='identifier_fmt',
IMO we shouldn't be saving a few characters in something that is user visible.  I strongly suggest (I'm begging, really :smile: ) that you use `identifier_format` instead.

2021-11-22 14:23 UTC, clebergnu commented on avocado/core/nrunner.py
> +        fmt = self.config.get("runner.identifier_fmt")
This is part of a much longer discussion that I intended to revisit and write a better explanation about it.... but, let me try to add some early context: IMO we need to better define what controls a runnable's behavior, in an explicit way. Having Avocado's entire configuration is not the right granularity IMO, and it makes it virtually IMPOSSIBLE to "replay" a runnable by executing `avocado-runner-$kind runnable-run`, which IMO is a nice check for the simplicity of the overall solution.

But, until that is better explained, and discussed, and hopefully improved, this LGTM.

2021-11-22 14:31 UTC, clebergnu requested changes
I'd like to see some type of test for this feature. Also, a quick explanation on how this will be used (or not conflict) with the "external runner"-like feature for nrunner would be welcome (just as a commit message or PR comment).

2021-11-23 16:51 UTC, beraldoleal commented
Sending v2. thanks.

2021-11-23 16:51 UTC, closed without merging