Update asset.py for optimizing the misinformation about hash warn
avocado-framework/avocado pull request #5172
Opened 2021-12-03 10:30 UTC by wangxiaorou92

Signed-off-by: wangxiaorou <wangxiaorou@uniontech.com>

2021-12-03 11:35 UTC, beraldoleal requested changes

2021-12-03 11:35 UTC, beraldoleal commented on avocado/utils/asset.py
> +        self.asset_hash = result
Hi @wangxiaorou92 thanks for contributing here. Could you please better describe the actual problem that you are solving here? Do you have an issue to link with details?

2022-01-10 14:06 UTC, ana commented
Hi @wangxiaorou92 ! This has been open for more a month without progress. Are you still insterested in this PR?

2022-02-03 12:02 UTC, ana commented
Hi @wangxiaorou92 
I'm closing this PR, feel free to resubmit it.  And if you do, please don't forget:
* describe the actual problem that you are solving here
* rebase the code in the top of the master branch
* add a meaningful commit message

2022-02-03 12:02 UTC, closed without merging