spawners: introduce AVOCADO_SPAWNER_EGG
avocado-framework/avocado pull request #5196
Opened 2021-12-14 13:18 UTC by beraldoleal

When using an isolated spawner (i.e: Podman), sometimes we need to test our
local branch on the isolated environment side. By default, Avocado will try to
download the matching eggs from our Git repository (or use the cached version).
But this will not apply your local changes at this point. You can build
your local egg with `python setup.py bdist_egg` and use the result as
input for this variable so Avocado will skip the downloading process and
use the local egg.

Since this is a "development feature", IMO a configuration option is not
necessary and we could use environment variables for that, keeping the
configuration options reserved for end users.

Fixes #5072, #4934.

Signed-off-by: Beraldo Leal <bleal@redhat.com>

2021-12-15 09:03 UTC, richtja reviewed
LGTM, I found just small typo.

2021-12-15 15:17 UTC, clebergnu commented
I'm trying to understand why this isn't simply a configuration item?  It'd use a self documenting mechanism, and other users should be able to refer to alternative eggs themselves (maybe hosted remotely). IMO, this is similar to `--podman-spawner-image` where users get to select which image to use, so they can select which avocado egg to use.

I understand this is born out of out development needs, but I can't see why this won't be a "first class" feature.

2022-01-19 17:27 UTC, beraldoleal commented
> I'm trying to understand why this isn't simply a configuration item? It'd use a self documenting mechanism, and other users should be able to refer to alternative eggs themselves (maybe hosted remotely). IMO, this is similar to `--podman-spawner-image` where users get to select which image to use, so they can select which avocado egg to use.
> 
> I understand this is born out of out development needs, but I can't see why this won't be a "first class" feature.

Hi @clebergnu, Sorry for the delay here.

I tough about implementing as you suggested at the time. However after a while I decided for this approach because I could not find a good use case where *users* would need to change the egg (differently of the spawner-image). Since this is covering a "development time need", maybe we could reduce the number of command line options, making our command line simpler by "hiding" those settings from end-users.

If you think this could be useful for end-users, then I'm fine with the change.

Makes any sense to you?

(PS: I'm strongly against your proposal, just trying to make things a little bit easier for users here)

2022-01-20 23:34 UTC, clebergnu commented
> > I'm trying to understand why this isn't simply a configuration item? It'd use a self documenting mechanism, and other users should be able to refer to alternative eggs themselves (maybe hosted remotely). IMO, this is similar to `--podman-spawner-image` where users get to select which image to use, so they can select which avocado egg to use.
> > I understand this is born out of out development needs, but I can't see why this won't be a "first class" feature.
> 
> Hi @clebergnu, Sorry for the delay here.
> 
> I tough about implementing as you suggested at the time. However after a while I decided for this approach because I could not find a good use case where _users_ would need to change the egg (differently of the spawner-image). Since this is covering a "development time need", maybe we could reduce the number of command line options, making our command line simpler by "hiding" those settings from end-users.
> 

I think there may be use cases for "regular users" to choose a different egg... Even if someone is not developing Avocado, there may be the need to deploy a slightly different version. But, the essence of my suggestion is that:

1. we already have a standard and self documenting configuration system
2. as a framework, we should give introduce more mechanisms and less policies

And if growing the command line itself is deemed to be a problem, we also already deal with that by having configuration items that are controlled by the configuration file, but do not have an equivalent command line switch.

> If you think this could be useful for end-users, then I'm fine with the change.
> 

I think it would, and just by being using the standard configuration system, it'd improve user's experience.

> Makes any sense to you?
> 
> (PS: I'm strongly against your proposal, just trying to make things a little bit easier for users here)

I assume you meant *not* strongly against my proposal. ;)

2022-01-21 12:07 UTC, beraldoleal commented
> I assume you meant not strongly against my proposal. ;)

Of course! :)

2022-01-24 18:12 UTC, clebergnu requested changes
Hi @beraldoleal,

The changes look good (thanks!) but the documentation is now inaccurate.  Given that, by using `settings` there's automatic generated documentation, I don't think it'd be a problem to remove the hand written doc section (but it's up to you).

2022-01-24 18:38 UTC, beraldoleal commented
@clebergnu fixed. thanks.

2022-01-24 18:57 UTC, clebergnu requested changes
Hi @beraldoleal,

The change in `docs/source/guides/contributor/index.rst` is not needed anymore. Other than that, LGTM.

2022-01-25 07:25 UTC, ana commented on avocado/plugins/spawners/podman.py
> +        help_msg = ('Avocado EGG path to be used during initial boostrap '
bootstrap*

2022-01-25 08:15 UTC, ana commented
The commit title says "introduce hability" that should be "introduce (the) ability".
Also please, consider changing  "Avocado EGG" for "Avocado egg" in the help message. It's parsed as a some acronym instead of a name.

2022-01-27 13:47 UTC, ana commented
Hi @beraldoleal,
this looks good to me, just missing this from @clebergnu :

> The change in `docs/source/guides/contributor/index.rst` is not needed anymore. Other than that, LGTM.

2022-01-27 13:52 UTC, beraldoleal commented
> Hi @beraldoleal, this looks good to me, just missing this from @clebergnu :
> 
> > The change in `docs/source/guides/contributor/index.rst` is not needed anymore. Other than that, LGTM.

I removed the content and forgot to remove this from the index. Just did with the force-push. Thanks.

2022-01-27 14:19 UTC, ana approved these changes

2022-01-28 04:06 UTC, clebergnu approved these changes
Thanks for the updates @beraldoleal, LGTM!

2022-01-28 04:07 UTC, merged