Removal of duplicates between requirements
avocado-framework/avocado pull request #5223
Opened 2022-01-04 16:21 UTC by richtja

This will make `RuntimeTask` comparable. It is used for removal of
requirement duplicates from runtime_tasks list. This is part of
preparations for dependency graph from BP004.

Reference: #5202
Signed-off-by: Jan Richter <jarichte@redhat.com>

2022-01-05 14:18 UTC, ana approved these changes

2022-01-05 14:22 UTC, richtja commented on avocado/plugins/runner_nrunner.py
> +        # remove duplicates form runtime_tasks
Thanks, I will fix it.

2022-01-11 17:12 UTC, clebergnu requested changes
After this change, the following *broken* test would pass:

```diff
diff --git a/selftests/unit/test_task_runtime.py b/selftests/unit/test_task_runtime.py
index 10894f3e1..23a46d9e7 100644
--- a/selftests/unit/test_task_runtime.py
+++ b/selftests/unit/test_task_runtime.py
@@ -22,3 +22,7 @@ class Runtime(TestCase):
         self.assertEqual(self.runtime_task.task.runnable.kind, 'noop')
         self.assertEqual(self.runtime_task.task.runnable.uri, 'noop')
         self.assertEqual(self.runtime_task.status, 'LOST CONTACT')
+
+    def test_equal(self):
+        self.assertEqual(self.runtime_task,
+                         RuntimeTask(Task(Runnable('exec', 'noop'), '1-noop')))
```

I understand the uniqueness of identifiers is being guaranteed by the suite code, but since we're adding the comparison logic here, we should cover the exceptional cases too. 

I think we should consider adding comparisons to the "lower level" structures such as `Task` and possibly even `Runnable`.

2022-01-12 09:22 UTC, richtja commented
> After this change, the following _broken_ test would pass:
> 
> ```diff
> diff --git a/selftests/unit/test_task_runtime.py b/selftests/unit/test_task_runtime.py
> index 10894f3e1..23a46d9e7 100644
> --- a/selftests/unit/test_task_runtime.py
> +++ b/selftests/unit/test_task_runtime.py
> @@ -22,3 +22,7 @@ class Runtime(TestCase):
>          self.assertEqual(self.runtime_task.task.runnable.kind, 'noop')
>          self.assertEqual(self.runtime_task.task.runnable.uri, 'noop')
>          self.assertEqual(self.runtime_task.status, 'LOST CONTACT')
> +
> +    def test_equal(self):
> +        self.assertEqual(self.runtime_task,
> +                         RuntimeTask(Task(Runnable('exec', 'noop'), '1-noop')))
> ```
> 
> I understand the uniqueness of identifiers is being guaranteed by the suite code, but since we're adding the comparison logic here, we should cover the exceptional cases too.

Hi @clebergnu I am not sure if the comparison logic should be solving such problem. Because IMO, the  uniqueness of identifiers has to be guaranteed. Two same identifiers for different tasks is an ERROR.

> 
> I think we should consider adding comparisons to the "lower level" structures such as `Task` and possibly even `Runnable`.

Yes, I was thinking about that, but I faced a problem with python `hash` method, because [the python is using different seed for different processes in hash()](https://docs.python.org/3/reference/datamodel.html#:~:text=By%20default%2C%20the,invocations%20of%20Python.). This cause troubles inside `sate machine` because the hash of the same task wasn't same in different processes.  To avoid this problem, we have to create specific hashing function for tasks and I wanted to avoid such solution.

2022-01-17 14:16 UTC, clebergnu approved these changes
Hi @richtja ,

I tried to come up with a simple version of what I meant, but it turned out to be much more complex than I wanted.  If I manage to come up with a simpler and better version of my idea, I'll send it on top of this.

Thanks!

2022-01-17 14:16 UTC, merged