nrunner: adding an external runner example (v2)
avocado-framework/avocado pull request #5235
Opened 2022-01-19 18:45 UTC by beraldoleal

This is a rough substitute for our external runner cases using the power
of our Job API.

Fixes #5137.

Signed-off-by: Beraldo Leal <bleal@redhat.com>
Signed-off-by: Cleber Rosa <crosa@rehdat.com>

#### Changes from v1:

 - Added documentation about external runner back
 - Added support to multiple references

2022-01-26 23:26 UTC, clebergnu requested changes
Besides the minor documentation typo, LGTM.

2022-01-26 23:26 UTC, clebergnu commented on docs/source/guides/user/chapters/advanced.rst
> +  $ $ avocado-external-runner curl redhat.com "google.com -v"
Duplicate `$` here.

2022-01-27 12:44 UTC, ana approved these changes
I made a test and it works exactly as the documentation says.
Except for the typo mentioned by @clebergnu this looks good.

2022-01-28 04:04 UTC, clebergnu approved these changes
LGTM, thanks!

2022-01-28 04:06 UTC, merged