Option --show fix
avocado-framework/avocado pull request #5316
Opened 2022-04-07 14:57 UTC by richtja

This adds the ability for the runners to print user-specific logging
streams to the console when the --show command is used.

It is backport of https://github.com/avocado-framework/avocado/commit/e2652b71668068838ea856bb7e16b262d34a511e and https://github.com/avocado-framework/avocado/commit/ddd143e2e928fa326dcd9ee65a942087207c5748.

Signed-off-by: Jan Richter [jarichte@redhat.com](mailto:jarichte@redhat.com)

2022-04-08 10:26 UTC, ana commented on avocado/core/messages.py
> +    """
nitpick: could you please add the extra lines between the descriptions, parameters and example?

2022-04-08 10:36 UTC, ana approved these changes
I tested it and this looks good to me.

2022-04-08 12:52 UTC, ana commented
@richtja I took a quick look to the failure of ` debian_version container:ubuntu:18.04` . I didn't find exactly why it fails, but it seems for older distros it needs pinning markupsafe, see: https://github.com/avocado-framework/avocado/pull/5321

2022-04-08 12:53 UTC, ana requested changes
See comment on failure debian_version container:ubuntu:18.04

2022-10-13 02:09 UTC, clebergnu approved these changes
LGTM, thanks!

2022-10-13 02:09 UTC, merged