fix data_factory.py
avocado-framework/avocado pull request #5424
Opened 2022-07-11 07:46 UTC by wangp-h

![企业微信截图_16575253716941](https://user-images.githubusercontent.com/42006321/178213681-9a5b99ae-0481-44f1-a2e4-3a0db16fe3a4.png)
When use funciton make_dir_and_populate to create a directory in basedir and populate with a number of files,
raise TypeError: a bytes-like object is required, not 'str'
fix this bug

2022-07-12 08:47 UTC, richtja requested changes
Hi @wangp-h thanks, for this change the code LGTM, but can you add the commit message and your signature, based on our [contributor guide](https://avocado-framework.readthedocs.io/en/latest/guides/contributor/chapters/styleguides.html#commit-style-guide), so the Static checks can pass. Thanks

2022-07-14 07:13 UTC, wangp-h commented
> Hi @wangp-h thanks, for this change the code LGTM, but can you add the commit message and your signature, based on our [contributor guide](https://avocado-framework.readthedocs.io/en/latest/guides/contributor/chapters/styleguides.html#commit-style-guide), so the Static checks can pass. Thanks

Hi,@richtja I have modified, please check

2022-07-14 08:24 UTC, richtja requested changes
Hi @wangp-h thanks for the changes, but can you add the same info from PR message to commit message. Information about why this change was made will be very useful in the future, when someone else will be going through history to understand the changes. Thank you.

2022-07-14 08:53 UTC, wangp-h commented
> Hi @wangp-h thanks for the changes, but can you add the same info from PR message to commit message. Information about why this change was made will be very useful in the future, when someone else will be going through history to understand the changes. Thank you.

Hi,@richtja Thank you for your suggestion, I have revised it according to your opinion, please check again.

2022-07-14 09:13 UTC, richtja requested changes
@wangp-h thanks for the changes, but the style checks are still failing. Can you please do another update, thanks.

You have to stick our [Style guides](https://avocado-framework.readthedocs.io/en/latest/guides/contributor/chapters/styleguides.html#commit-style-guide) important part is:
`lines are limited to 72 characters per line.`

you can inspire by another commits in master branch like [this](https://github.com/avocado-framework/avocado/commit/bf9306fee9735f12254da80ae519679b6778f2d4)

I understand that sometimes the style checks might be frustrating, but it is very important for good shape of the project.

2022-07-14 09:27 UTC, wangp-h commented
> @wangp-h thanks for the changes, but the style checks are still failing. Can you please do another update, thanks.
> 
> You have to stick our [Style guides](https://avocado-framework.readthedocs.io/en/latest/guides/contributor/chapters/styleguides.html#commit-style-guide) important part is: `lines are limited to 72 characters per line.`
> 
> you can inspire by another commits in master branch like [this](https://github.com/avocado-framework/avocado/commit/bf9306fee9735f12254da80ae519679b6778f2d4)
> 
> I understand that sometimes the style checks might be frustrating, but it is very important for good shape of the project.

Hi,@richtja It has been revised, I am committing it for the first time, thank you for your correction

2022-07-14 11:49 UTC, richtja approved these changes
LGTM, thanks. Those  CI failures are not related to this PR. They are part of #5427

2022-07-26 11:21 UTC, merged