Drop "nrunner" prefix from config and parameters
avocado-framework/avocado pull request #5449
Opened 2022-07-28 16:21 UTC by clebergnu

The `--nrunner-$option`s made sense when the old runner was available. Nowadays, it's just more typing and confusion to users.

Also, this renames the `Runner` interface and `--test-runner` option to `SuiteRunner` and `--suite-runner`, to more accurately represent what they do.

2022-08-08 12:55 UTC, beraldoleal requested changes

2022-08-08 12:55 UTC, beraldoleal commented on avocado/plugins/run.py
> +            metavar="SUITE_RUNNER",
IIUC, this change is breaking our API in the sense that users might need some time to get used to it. So it looks like we need a deprecation warning + keep supporting this for a while.

2022-08-08 12:55 UTC, beraldoleal commented on avocado/core/nrunner/task.py
>          self.category = category
same here.

2022-10-21 02:15 UTC, clebergnu commented
The deprecation is implemented in #5493.  The actual change and removal of the old options will be done after the Avocado 99.0 release (to allow for one release with the deprecated options).

2022-10-21 02:15 UTC, closed without merging