Function is used to check the netmask value and convert it into shortform (/mask) of netmask values
avocado-framework/avocado pull request #5486
Opened 2022-09-08 08:59 UTC by TasmiyaNalatwad

Function is used to check the netmask value and convert it into shortform (/mask) of netmask values
Example : 255.255.255.0 = /24
255.255.252.0 = /22

Signed-off-by: Tasmiya Nalatwad <tasmiya@linux.vnet.ibm.com>

2022-09-14 13:06 UTC, PraveenPenguin commented
@TasmiyaNalatwad can you please address Travis error

2022-09-29 05:44 UTC, abdhaleegit requested changes

2022-09-29 05:44 UTC, abdhaleegit commented on avocado/utils/network/interfaces.py
> +        :return : Returns /mask value of given netmask
Why return /  , I would suggest return only integer value

2022-09-29 05:44 UTC, abdhaleegit commented on avocado/utils/network/interfaces.py
> +        :return : Returns /mask value of given netmask
Append / in test case

2022-09-29 05:44 UTC, abdhaleegit commented on avocado/utils/network/interfaces.py
> +        :return : Returns /mask value of given netmask
Add return type in doc string

2022-09-29 05:44 UTC, abdhaleegit commented on avocado/utils/network/interfaces.py
> +        return(sum([bin(int(bits)).count("1") for bits in netmask.split(".")]))
Reformat return, space between return and operation

2022-09-30 09:39 UTC, abdhaleegit requested changes

2022-09-30 09:39 UTC, abdhaleegit commented on avocado/utils/network/interfaces.py
> +        """ Function is used to check the netmask value and convert
insert a empty line after, the reason why travis is failing.. refer to other methods doc string inthis file

2022-09-30 11:22 UTC, abdhaleegit approved these changes
LGTM

2022-10-18 03:42 UTC, PraveenPenguin approved these changes

2022-10-18 03:42 UTC, merged