Adding support for IP and NETMASK address validation
avocado-framework/avocado pull request #5541
Opened 2022-12-05 02:44 UTC by FarooqAbdulla01

This feature enables to validate the IP address format interms of IP address and IP octet range.
And also enables to validate the Netmask address format interms of Netmask address, octec range and invalid netmask ranges

Signed-off-by: Shaik Abdulla <Shaik.Abdulla1@ibm.com>

2022-12-20 14:31 UTC, richtja requested changes
Hi @FarooqAbdulla01, thank you for your contribution, the code LGTM. Can you please fix the static-checks, thanks. You can run them on your machine by `python setup.py test --select=static-checks`

2023-01-09 05:53 UTC, abdhaleegit commented
@PraveenPenguin @richtja we are good to merge now

2023-01-09 09:16 UTC, richtja approved these changes
Hi @FarooqAbdulla01 and @abdhaleegit, thank you for the fixes it LGTM. Right now we are in feature-freeze and we are running the pre-release tests and we will release new avocado version this week. Because of this process, I will merge it after the release.

2023-01-18 10:41 UTC, PraveenPenguin approved these changes

2023-01-18 10:41 UTC, merged