Unmounting of symbolic mountpoints
avocado-framework/avocado pull request #5582
Opened 2023-01-20 09:20 UTC by AYUSHJAIN951

Mountpoint symbolic links also needs to be searched while getting mountpoint and removal of those are also needed.

Signed-off-by: ayushjain951 <ayush.jain3@amd.com>

2023-01-20 10:23 UTC, richtja requested changes
Hi @AYUSHJAIN951 the change LGTM, please update your changes to correspond to our style checks. All you need to do is run `black .` in avocado root directory and `black` will update your changes. Also, you can run style checks on your machine by `python setup.py test --select=static-checks`

2023-01-20 22:46 UTC, AYUSHJAIN951 commented
> Hi @AYUSHJAIN951 the change LGTM, please update your changes to correspond to our style checks. All you need to do is run `black .` in avocado root directory and `black` will update your changes. Also, you can run style checks on your machine by `python setup.py test --select=static-checks`

@richtja I think that styling issue is resolved now and thanks for the guidance,

2023-01-23 05:01 UTC, PraveenPenguin approved these changes

2023-01-23 09:20 UTC, richtja approved these changes
LGTM, thanks

2023-01-23 09:20 UTC, merged