Added validate Mac address functions to utility.
avocado-framework/avocado pull request #5605
Opened 2023-02-08 12:59 UTC by manvanthar

Added validate Mac address functions to utility.

With misc tests changing from interface based to MAC address need this function to validate the MAC is valid.

Signed-off-by: Manvanthara B Puttashankar <manvanth@linux.vnet.ibm.com>

2023-02-08 12:59 UTC, manvanthar commented
Valid MAC address:
            36:84:37:5a:ea:02

        Invalid MAC address:
            3684375aea02
            36:84:37-5a-ea-02
            36-84-37-5a-ea-02
            36.84.37.5a.ea

2023-02-08 14:01 UTC, PraveenPenguin reviewed
@manvanthar thanks for patch ,can you please address the style  issue which is explained here 

https://github.com/avocado-framework/avocado/actions/runs/4124346912/jobs/7123826023#step:8:56

2023-02-08 14:54 UTC, FarooqAbdulla01 commented on avocado/utils/network/interfaces.py
> +
@manvanthar validation fails for "36:84:37:5a:ea:0ff", will have limit to 2 digits after colon with regex match.

2023-02-09 04:54 UTC, abdhaleegit requested changes
just slight change in function name, also the parameter name can be mac_id instead mac_str

2023-02-09 04:54 UTC, abdhaleegit commented on avocado/utils/network/interfaces.py
> +    def validate_macaddr(self, mac_str):
please change it to validate_mac_addr just for readability., rest all looks good

2023-02-09 05:50 UTC, FarooqAbdulla01 commented
validation failing for "3684375aea02" MAC address format.

following is the mac address set am validating against it.

validate_macaddr("36:84:37-5a-ea-02")
validate_macaddr("36-84-37-5a-ea-02")
validate_macaddr("3684375aea02")   ---> failing for this format, rest looks good.
validate_macaddr("36.84.37.5a.ea")
validate_macaddr("36:84:37:5a:ea:0ff")

2023-02-09 05:53 UTC, manvanthar commented
> validation failing for "3684375aea02" MAC address format.
> 
> following is the mac address set am validating against it.
> 
> validate_macaddr("36:84:37-5a-ea-02") validate_macaddr("36-84-37-5a-ea-02") validate_macaddr("3684375aea02") ---> failing for this format, rest looks good. validate_macaddr("36.84.37.5a.ea") validate_macaddr("36:84:37:5a:ea:0ff")

It is updated in the comment on valid v/s invalid acceptable values.

2023-02-09 08:38 UTC, abdhaleegit commented
@manvanthar I was trying to test the, please move this network/host.py the reason being the interface.py gets instantiated only when after a valid mac mapped to interface. so in our tests we have to exit way before this. so please move 
sorry for last minute change

2023-02-10 17:26 UTC, manvanthar commented
> @manvanthar I tested the code, please move this to network/host.py (after get_interface_by_hwaddr) the reason being the interface.py gets instantiated only when after a valid mac mapped to interface. so in our tests we have to exit way before this. so please move
> sorry for last minute change

Sure Abdul. Have sent the updated code!

2023-02-13 13:14 UTC, PraveenPenguin approved these changes
LGTM

2023-02-13 14:01 UTC, abdhaleegit approved these changes
LGTM, tested with latest changes

```
JOB ID     : d4e4ebcac5e554f8faf753c6b778df551c3e7659
JOB LOG    : /home/OpTest/avocado-fvt-wrapper/results/job-2023-02-13T07.49-d4e4ebc/job.log
 (01/15) ethtool_test.py:Ethtool.test_ethtool;run-args-PrivateFlag-18ea: STARTED
 (01/15) ethtool_test.py:Ethtool.test_ethtool;run-args-PrivateFlag-18ea: PASS (14.55 s)
 (02/15) ethtool_test.py:Ethtool.test_ethtool;run-args-Driver-b3f8: STARTED
 (02/15) ethtool_test.py:Ethtool.test_ethtool;run-args-Driver-b3f8: PASS (8.34 s)
 (03/15) ethtool_test.py:Ethtool.test_ethtool;run-args-Autonegotiation-f53d: STARTED
 (03/15) ethtool_test.py:Ethtool.test_ethtool;run-args-Autonegotiation-f53d: PASS (22.98 s)
 (04/15) ethtool_test.py:Ethtool.test_ethtool;run-args-PauseParameter-3cac: STARTED
 (04/15) ethtool_test.py:Ethtool.test_ethtool;run-args-PauseParameter-3cac: PASS (12.35 s)
 (05/15) ethtool_test.py:Ethtool.test_ethtool;run-args-Coalescing-20f7: STARTED
 (05/15) ethtool_test.py:Ethtool.test_ethtool;run-args-Coalescing-20f7: PASS (12.45 s)
 (06/15) ethtool_test.py:Ethtool.test_ethtool;run-args-RingParameter-a769: STARTED
 (06/15) ethtool_test.py:Ethtool.test_ethtool;run-args-RingParameter-a769: PASS (12.32 s)
 (07/15) ethtool_test.py:Ethtool.test_ethtool;run-args-ShowOffloadProtocolFeature-b20b: STARTED
 (07/15) ethtool_test.py:Ethtool.test_ethtool;run-args-ShowOffloadProtocolFeature-b20b: PASS (13.27 s)
 (08/15) ethtool_test.py:Ethtool.test_ethtool;run-args-AdapterInitiate-26f1: STARTED
 (08/15) ethtool_test.py:Ethtool.test_ethtool;run-args-AdapterInitiate-26f1: PASS (19.60 s)
 (09/15) ethtool_test.py:Ethtool.test_ethtool;run-args-Statistics-3174: STARTED
 (09/15) ethtool_test.py:Ethtool.test_ethtool;run-args-Statistics-3174: PASS (12.40 s)
 (10/15) ethtool_test.py:Ethtool.test_ethtool;run-args-SelfTest-4acd: STARTED
 (10/15) ethtool_test.py:Ethtool.test_ethtool;run-args-SelfTest-4acd: PASS (22.11 s)
 (11/15) ethtool_test.py:Ethtool.test_ethtool;run-args-Show-permaddr-b691: STARTED
 (11/15) ethtool_test.py:Ethtool.test_ethtool;run-args-Show-permaddr-b691: PASS (12.40 s)
 (12/15) ethtool_test.py:Ethtool.test_ethtool;run-args-Show-time-stamping-ca91: STARTED
 (12/15) ethtool_test.py:Ethtool.test_ethtool;run-args-Show-time-stamping-ca91: PASS (12.32 s)
 (13/15) ethtool_test.py:Ethtool.test_ethtool;run-args-Get-phy-tunable-7b4c: STARTED
 (13/15) ethtool_test.py:Ethtool.test_ethtool;run-args-Get-phy-tunable-7b4c: WARN: Test passed but there were warnings during execution. Check the log for details. (12.63 s)
 (14/15) ethtool_test.py:Ethtool.test_ethtool;run-args-Show-channels-cba0: STARTED
```

2023-02-14 05:02 UTC, merged