DependencyResolver output fix
avocado-framework/avocado pull request #5673
Opened 2023-05-02 12:18 UTC by richtja

The `DependencyResolver` task created its own output directory in `test-results` dir. This will connect outputs of the Test task and its `DependencyResolver` task, so both of those tasks will have output in the one directory together.

Reference: #5671

2023-05-11 03:50 UTC, clebergnu requested changes
@richtja this is an improvement, because on failures, there's no directory in `test-results` that are named after the non-test tasks.  Example:

```
$ avocado run examples/tests/passtest_with_dependency.py 
JOB ID     : 2b11715721a00d8c53790904d29acf5d5cbc71db
JOB LOG    : /home/cleber/avocado/job-results/job-2023-05-10T23.46-2b11715/job.log
RESULTS    : PASS 0 | ERROR 0 | FAIL 0 | SKIP 1 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /home/cleber/avocado/job-results/job-2023-05-10T23.46-2b11715/results.html
JOB TIME   : 2.68 s

$ ls /home/cleber/avocado/job-results/job-2023-05-10T23.46-2b11715/test-results/
1-examples_tests_passtest_with_dependency.py_PassTest.test
```

But, there is still a test directory, when no test was attempted to be executed (its dependency failed).  According to issue #5671:

**Expected behavior**
_If no test is executed, test-results should be empty._

Also, the content of that directory contains the dependency task output:

```
cat /home/cleber/avocado/job-results/job-2023-05-10T23.46-2b11715/test-results/1-examples_tests_passtest_with_dependency.py_PassTest.test/stderr 
Failed to install hello. Check the package(s) name and if sudo permission is granted.
```

2023-05-11 09:02 UTC, richtja commented
> @richtja this is an improvement, because on failures, there's no directory in `test-results` that are named after the non-test tasks. Example:
> 
> ```
> $ avocado run examples/tests/passtest_with_dependency.py 
> JOB ID     : 2b11715721a00d8c53790904d29acf5d5cbc71db
> JOB LOG    : /home/cleber/avocado/job-results/job-2023-05-10T23.46-2b11715/job.log
> RESULTS    : PASS 0 | ERROR 0 | FAIL 0 | SKIP 1 | WARN 0 | INTERRUPT 0 | CANCEL 0
> JOB HTML   : /home/cleber/avocado/job-results/job-2023-05-10T23.46-2b11715/results.html
> JOB TIME   : 2.68 s
> 
> $ ls /home/cleber/avocado/job-results/job-2023-05-10T23.46-2b11715/test-results/
> 1-examples_tests_passtest_with_dependency.py_PassTest.test
> ```
> 
> But, there is still a test directory, when no test was attempted to be executed (its dependency failed). According to issue #5671:
> 
> **Expected behavior** _If no test is executed, test-results should be empty._
> 
> Also, the content of that directory contains the dependency task output:
> 
> ```
> cat /home/cleber/avocado/job-results/job-2023-05-10T23.46-2b11715/test-results/1-examples_tests_passtest_with_dependency.py_PassTest.test/stderr 
> Failed to install hello. Check the package(s) name and if sudo permission is granted.
> ```
Hi @clebergnu, thanks for the review. I am not sure if the behavior from https://github.com/avocado-framework/avocado/issues/5671 is correct. IMO if test is skipped because of dependency failure, the logs of this failure have to be stored somewhere for debugging purposes. If we remove those logs, then find out why the test has been skipped will be much harder.

2023-05-23 17:05 UTC, clebergnu commented
> > @richtja this is an improvement, because on failures, there's no directory in `test-results` that are named after the non-test tasks. Example:
> > ```
> > $ avocado run examples/tests/passtest_with_dependency.py 
> > JOB ID     : 2b11715721a00d8c53790904d29acf5d5cbc71db
> > JOB LOG    : /home/cleber/avocado/job-results/job-2023-05-10T23.46-2b11715/job.log
> > RESULTS    : PASS 0 | ERROR 0 | FAIL 0 | SKIP 1 | WARN 0 | INTERRUPT 0 | CANCEL 0
> > JOB HTML   : /home/cleber/avocado/job-results/job-2023-05-10T23.46-2b11715/results.html
> > JOB TIME   : 2.68 s
> > 
> > $ ls /home/cleber/avocado/job-results/job-2023-05-10T23.46-2b11715/test-results/
> > 1-examples_tests_passtest_with_dependency.py_PassTest.test
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > But, there is still a test directory, when no test was attempted to be executed (its dependency failed). According to issue #5671:
> > **Expected behavior** _If no test is executed, test-results should be empty._
> > Also, the content of that directory contains the dependency task output:
> > ```
> > cat /home/cleber/avocado/job-results/job-2023-05-10T23.46-2b11715/test-results/1-examples_tests_passtest_with_dependency.py_PassTest.test/stderr 
> > Failed to install hello. Check the package(s) name and if sudo permission is granted.
> > ```
> 
> Hi @clebergnu, thanks for the review. I am not sure if the behavior from #5671 is correct. IMO if test is skipped because of dependency failure, the logs of this failure have to be stored somewhere for debugging purposes. If we remove those logs, then find out why the test has been skipped will be much harder.

I agree that we should keep information that explains why tests were not attempted to be run.  But, as it stands, we are dropping information in the directory that is about the *test* itself, and not about their dependencies.  This can be very confusing to users.

I see two possibilities (in order of my personal preference):

1. A separate directory structure, within the job results directory, mimicking the task dependency graph structure (possibly with some simplifications) with each task results there.
2. A sub-directory named such as `dependencies` within the `test-results/$test-id` path.

The most important thing is not mixing the output from the dependencies with the output from the test itself.  I'll admit that the point about not even having a `test-results/$test-id` directory as described in #5671 is somewhat purist and not 100% practical.

2023-06-06 12:32 UTC, richtja commented
Hi @clebergnu, thank you for your review. After our discussion I created a new version in #5701, please take a look.

2023-06-06 12:32 UTC, closed without merging