Add a quick guide for setting up the remote spawner
avocado-framework/avocado pull request #5846
Opened 2023-12-28 18:23 UTC by clebergnu

This Documents some crucial steps for a new user of the remote spawner plugin.

Reference: https://github.com/avocado-framework/avocado/issues/5838

2023-12-28 19:24 UTC, richtja requested changes
Hi @clebergnu, thank you for this update. I have just one proposal about aexpect, what do you think?

2023-12-28 19:24 UTC, richtja commented on optional_plugins/spawner_remote/README.rst
> +This plugin makes use of remote aexpect sessions (to remote hosts or
Can you please add a link to aexpect repository, users might not be aware of it and a link could help here.

2023-12-29 10:03 UTC, pevogam approved these changes
Great @clebergnu, I have to confess I did not expect this extra step on your side but the documentation is both succinct and extensive and other than a few minor typos I say LGTM.

2023-12-29 10:03 UTC, pevogam commented on optional_plugins/spawner_remote/README.rst
> +After installed, add the slot to your avocado config file::
*After it is installed*

2023-12-29 10:03 UTC, pevogam commented on optional_plugins/spawner_remote/README.rst
> +After installed, add the slot to your avocado config file::
Add *a slot (e.g. "board")* to your avocado config file

2024-01-02 14:56 UTC, clebergnu commented
updated with @richtja and @pevogam comments/requests.

2024-01-02 15:31 UTC, richtja approved these changes
LGMT, thanks for the update.

2024-01-02 15:32 UTC, merged