AvocadoConfigParser
avocado-framework/avocado pull request #5859
Opened 2024-01-23 14:57 UTC by richtja

This commit introduces `AvocadoConfigParser` which uses `configparser.ConfigParser` to parse INI files with avocado configuration. During the parsing process, it preserves the config files path, which is used for creating error messages when the files are badly formatted. And it removes the `config` file from jobdata directory since it is not used anymore.

Before this PR:
```
...
  File "<unknown>", line 2
    foo moo
    ^^^
SyntaxError: invalid syntax

```
After this PR:
```
...
    raise SyntaxError(
SyntaxError: Syntax error in config file ../testing/config, please check the value ["CANCEL", "SKIP", "FAIL"]
foo moo
```
Reference: #5857 #5643

2024-01-25 20:15 UTC, clebergnu requested changes
Hi @richtja , thanks for this! Other than the typo, this LGTM.

2024-01-25 20:15 UTC, clebergnu commented on avocado/core/settings.py
> +    """AvocadoConfigParser uses ConfigPraser to parse config from INI files.
Typo: "Praser"

2024-01-25 20:15 UTC, clebergnu commented on avocado/core/settings.py
> +    The configuration from files is stored in dict like structure
"in *a* dict-like structure"

2024-01-26 11:25 UTC, richtja commented
Hi @clebergnu thank you for your review. I fixed those typos with a `force-push`. Please have a look.

2024-01-29 10:15 UTC, clebergnu approved these changes
LGTM, thanks!

2024-01-29 10:15 UTC, merged