avocado/core/parameters.py Delete redundant conditional statements
avocado-framework/avocado pull request #5878
Opened 2024-03-05 01:55 UTC by zuohanxu

avocado/core/parameters.py 
Delete redundant conditional statements

2024-03-11 08:05 UTC, zuohanxu commented
Hi,@clebergnu:

2024-03-11 08:07 UTC, zuohanxu commented
Hi, @clebergnu , Could you please help me check the pr I submitted ?

2024-03-11 11:48 UTC, richtja requested changes
Hi @zuohanxu thank you for your contribution, it is always welcome. You are definitely right that from code view this is redundant, and we should remove it. The issue with this change is that `get()` method is the main API for avocado-instrumented test writers to access test parameters, see [avocado doc](https://avocado-framework.readthedocs.io/en/latest/guides/writer/chapters/parameters.html#avocadoparams). 

Because this is an open API for our users, we can't change it without warning them, because we don't know if anybody uses `self.params.get(param_name, path=None)`

IMO, we have two possibilities here:
1. Change the API and support `None` option for next release with warning message. Something like this:
```
def get(self, key, path="*", default=None):
        """
        Retrieve value associated with key from params
        :param key: Key you're looking for
        :param path: namespace ['*']
        :param default: default value when not found
        :raise KeyError: In case of multiple different values (params clash)
        """
        if path is None:  # default path is any relative path
            path = "*"
            logging.getLogger(self._logger_name).warning("The path default value for params.get() has changed from None to "*".)
        try:
            ...
```
2. Leave it like it is.

I would prefer the second option, since I don't see a big issue with `path=None` and changing it might cause many issues for our users. @clebergnu what do you think?

2024-03-11 19:22 UTC, clebergnu requested changes
As @richtja has said, changes to the Avocado core API (anything available from an Avocado Instrumented Test) have to be done with the uttermost care.

This proposal would introduce a change in behavior if users were to explicitly pass `path=None`, that is, it would no longer mean "all paths".

I don't think the "clean up" justifies the change in behavior and the impact it can cause on existing users.

2024-03-12 03:32 UTC, zuohanxu commented
@clebergnu @richtja I agree with you and give up the revision. Now I have modified the code a little bit, which can reduce some unnecessary function calls, what do you think of this

2024-03-22 10:24 UTC, richtja approved these changes
@zuohanxu LGTM, thank you.

2024-03-22 10:25 UTC, merged