fix: Check if the port is available via socket.connect
avocado-framework/avocado pull request #5884
Opened 2024-03-21 10:50 UTC by PaulYuuu

The current implementation doesn't accurately determine if the port is
in use. We need to attempt a connection to the port rather than just
attempting to bind to it.

Also, fix some typo in the doc string.

Signed-off-by: Yihuang Yu <yihyu@redhat.com>

2024-03-21 15:04 UTC, clebergnu requested changes
Hi @PaulYuuu, thanks for this.

Can you please provide more detail on how/why you believe "The current implementation doesn't accurately determine if the port is in use." ?  I'm interested in an answer that describes the limitations of the `bind()` approach, that is, why you believe it can generate false positives.

AFAICT, you can not `listen()` at a port that someone else has `bind()` to.  The simplest test is opening two Python interpreters, with the first one:

```
>>> import socket
>>> s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
>>> s
<socket.socket fd=3, family=2, type=1, proto=0, laddr=('0.0.0.0', 0)>
>>> s.bind(('127.0.0.1', 9999))
>>> s
<socket.socket fd=3, family=2, type=1, proto=0, laddr=('127.0.0.1', 9999)>
```

Now, in a second silmultaneous session:

```
>>> import socket
>>> s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
>>> s
<socket.socket fd=3, family=2, type=1, proto=0, laddr=('0.0.0.0', 0)>
>>> s.bind(('127.0.0.1', 9999))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
OSError: [Errno 98] Address already in use
```

This is the behavior that is expected by the current implementation.  Can you please describe how it's not accurate?

Also, it'd be nice to move the docstring fixes to a commit of its own, just like you've done with the one about `FAMILIES` and `PROTOCOLS`.

2024-03-22 01:12 UTC, PaulYuuu commented
Sorry @clebergnu, I forgot to add a comment to introduce the background.

I submitted this PR due to a kernel bug, it may be related to https://github.com/torvalds/linux/commit/28044fc1d4953b07acec0da4d2fc4784c57ea6fb. So I think it's worth improving this function.

The reproducer is:
```shell
# /usr/libexec/qemu-kvm -M virt -cpu host --nodefaults -vnc :1

# netstat -tuln | grep 5901
tcp        0      0 0.0.0.0:5901            0.0.0.0:*               LISTEN
tcp6       0      0 :::5901                 :::*                    LISTEN
```

```python
>>> from socket import *
>>> s_v4 = socket(AF_INET, SOCK_STREAM)
>>> s_v6 = socket(AF_INET6, SOCK_STREAM)
>>> # IPv6 will refuse to bind
>>> s_v6.bind(('localhost', 5901))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
OSError: [Errno 98] Address already in use
>>> # IPv4 can successfully bind the port, but should not
>>> s_v4.bind(('localhost', 5901))
>>>
```

2024-03-22 01:13 UTC, PaulYuuu commented on avocado/utils/network/ports.py
> +        sock.close()
Yep, my mistake, will update it.

2024-03-22 01:20 UTC, PaulYuuu commented
avocado-vt will find free ports to VM, like vnc port 
```python
self.vnc_port = utils_misc.find_free_port(5900, 6900, sequent=True)
```

When defining the second VM, 5900 is already used but find_free_port still returns 5900, a workaround is to use `family=socket.AF_INET6`, but some systems may have no INET6 enablement.

2024-04-16 08:25 UTC, PaulYuuu commented
@clebergnu, can you take a look?

2024-04-23 03:26 UTC, closed without merging