Adding check if secureboot is enabled or not
avocado-framework/avocado pull request #5929
Opened 2024-05-08 18:04 UTC by vaishnavibhat

The function checks if secureboot is enabled or not from the OS side.
The command output of "lsprop /proc/device-tree/ibm,secure-boot" is used to check the OS status.

2024-05-10 06:48 UTC, abdhaleegit approved these changes
LGTM

2024-05-10 06:49 UTC, abdhaleegit commented
@vaishnavibhat fix static fails  make use of double qoutes here if '00000002' in line:

2024-05-10 12:51 UTC, richtja commented on avocado/utils/linux.py
> +    cmd = "lsprop /proc/device-tree/ibm,secure-boot"
Hi @vaishnavibhat, can you please describe to me what `lsprop` is and what it does, to be hones I am not familiar with it.

2024-05-23 09:38 UTC, vaishnavibhat commented
lsprop is a tool provided by powerpc-utils. It is used to get information about /proc files .

For secureboot check:
#lsprop /proc/device-tree/ibm,secure-boot
/proc/device-tree/ibm,secure-boot
00000002

0 incase of secure boot disabled, 1 (enable and log only - trusted boot) and 2 (enable and enforce - secure boot)

#man lsprop
LSPROP(8)                Linux on Power Service Tools                LSPROP(8)

NAME
       lsprop - list properties

SYNOPSIS
       lsprop [-R] [-m max-bytes] [-w num-words] [FILE...]

OVERVIEW
       lsprop  program  is a member of the ppc64-utils suite of utils.  Use it
       to list properties

DESCRIPTION
       lsprop displays properties for FILEs  like  Open  Firmware  .properties
       word.  If the FILE is not set, the current directory is used.

OPTIONS
       -R     Process recursively

       -m max-bytes
              Read only first max-bytes bytes from the FILEs

       -w num-words
              Display up to num-words words per line

Linux                              Sep 2010                          LSPROP(8)```

2024-05-23 11:49 UTC, richtja commented
> lsprop is a tool provided by powerpc-utils. It is used to get information about /proc files .
> 
> For secureboot check: #lsprop /proc/device-tree/ibm,secure-boot /proc/device-tree/ibm,secure-boot 00000002
> 
> 0 incase of secure boot disabled, 1 (enable and log only - trusted boot) and 2 (enable and enforce - secure boot)
> 
> #man lsprop LSPROP(8) Linux on Power Service Tools LSPROP(8)
> 
> NAME lsprop - list properties
> 
> SYNOPSIS lsprop [-R] [-m max-bytes] [-w num-words] [FILE...]
> 
> OVERVIEW lsprop program is a member of the ppc64-utils suite of utils. Use it to list properties
> 
> DESCRIPTION lsprop displays properties for FILEs like Open Firmware .properties word. If the FILE is not set, the current directory is used.
> 
> OPTIONS -R Process recursively
> 
> ```
>    -m max-bytes
>           Read only first max-bytes bytes from the FILEs
> 
>    -w num-words
>           Display up to num-words words per line
> ```
> 
> Linux Sep 2010 LSPROP(8)

Hi @vaishnavibhat thank you  for the description. So IIUIC the whole `is_os_secureboot_enabled` method will only work on powerpc. Therefore, I would propose to do an arch check and create and raise for example `UnsupportedMachineError`  for unsupported architectures.

2024-06-04 12:46 UTC, richtja requested changes
Hi @vaishnavibhat, thank you for your update. IMO, it is on the right track. I just think that `except Exception` is too general for this purpose, and we can be more specific. Please let me know what do you think about it.

2024-06-04 12:46 UTC, richtja commented on avocado/utils/linux.py
> +    except Exception:
I am not sure if `Exception` is not too general. When `lsprop` is not in the system, the `process.system_output(cmd) will throw `FileNotFoundError` am I right?

2024-06-26 11:23 UTC, abdhaleegit commented
@richtja We are good to merge now

2024-06-27 04:56 UTC, vaishnavibhat commented
Resending the patch after taking care of the review comments.

2024-06-28 07:09 UTC, PraveenPenguin approved these changes

2024-06-28 07:16 UTC, abdhaleegit commented
@richtja Please see if this is mergable

2024-07-01 10:06 UTC, vaishnavibhat commented
@richtja Addressed the review comments. Please me know if this looks good. 

Thank you

2024-07-08 11:05 UTC, richtja approved these changes
Hi @vaishnavibhat, after the updates it LGTM. Thank you.

2024-07-09 13:07 UTC, merged