Using the pathlib module to handle file paths enhances the readability and maintainability of the code
avocado-framework/avocado pull request #5979
Opened 2024-06-27 02:42 UTC by faker-king

Using pathlib can make file path operations more object-oriented and easy to understand, and have better compatibility across different operating systems.

2024-07-01 01:29 UTC, faker-king commented
hi @richtja, Can you help me see if I can merge the code

2024-07-09 13:36 UTC, richtja requested changes
Hi @faker-king please remove 9806712b4ec63399c72f7ca243f005aa00301637 and 1051bc0ec08f27be2dab31f7384053faadfc8898. IMO, they are not related to this PR. To be honest, I am not sure about usage of `pathlib` in one specific method of `asset` utility. Correct me if I am wrong, but I don't see any additional benefit in this change.

But you catch that we don't have exception handling for this file manipulation, and that would be a great update. Therefore, please add only the exception handling. Thanks

2024-07-09 13:36 UTC, richtja commented on avocado/utils/asset.py
> -        os.remove(filename)
I would keep the `os.remove`. I don't see any additional benefit with usage of `pathlib`, especially when it is inconsistent with other parts of asset utility which uses  `os.remove`.

2024-07-09 13:36 UTC, richtja commented on avocado/utils/asset.py
> +        except FileNotFoundError:
The exception handling is a great idea, and it is something which is needed here. Good job.

2024-07-26 08:56 UTC, faker-king commented
Hi @richtja, I am very sorry for the delay in modifying this PR. I have already made the necessary changes as per your request. Could you please double check.

2024-07-26 09:05 UTC, richtja requested changes
Hi @faker-king, thank you for your updates.  The overall changes LGTM, but you still have 9806712b4ec63399c72f7ca243f005aa00301637 and 1051bc0ec08f27be2dab31f7384053faadfc8898 commit which are not related to this PR, please drop those.

 Also, can you please update the title of ee32a501a4cd106bf13019bec5d5b721da379c91, from your description you are updating the exception handling to all os.remove calls, but this commit is only about `avocado/utils/asset.py`. Please be more specific. Thank you.

2024-08-28 02:47 UTC, faker-king commented
@richtja Due to some permission issues with my account, it was verified and I have made the necessary modifications as per your suggestion to see if it can be merged

2024-08-28 08:33 UTC, richtja commented
Hi @faker-king, thank you for your updates. I'm still missing the commit title update, your changes don't add exception handling to os.remove in the whole avocado project, it is located only to avocado/utils/asset.py. Can you please update the title to be more specific? Thank you.

2024-08-29 02:05 UTC, faker-king commented
@richtja Modified

2024-08-29 08:58 UTC, richtja commented
> @richtja Modified

Hi @faker-king, sorry but maybe I haven't expressed myself clearly, I was talking about commit headline. It is needed for easier search thought changes in commit history in the future. Can you please update the [commit headline](https://github.com/avocado-framework/avocado/pull/5979/commits/ae3d836fc7f8b42e0488e7712a06de211f1b2691) as well, thanks.

2024-08-29 09:25 UTC, faker-king commented
@richtja Haha, it's okay, I didn't understand either,  it has been modified.

2024-08-29 11:03 UTC, richtja approved these changes
Hi @faker-king, it LGTM now. Thanks for your changes.

2024-09-02 11:49 UTC, merged