Runnable identifier
avocado-framework/avocado pull request #5992
Opened 2024-08-01 14:05 UTC by richtja

This commit introduces a way how to explicitly specify runnable identifier through Job API or runnable recipe. This change shouldn't affect current behaviour and if the identifier is not specified it will be generated based on the `runner.identifier_format` config variable.

Reference: #5964

2024-08-02 06:54 UTC, clebergnu requested changes
Hi @richtja,

This LGTM, but I will ask you to consider:

* Adding one example of the identifier to the [recipes](https://avocado-framework.readthedocs.io/en/latest/guides/writer/chapters/recipes.html) documentation section
* Adding identifier example to `examples/nrunner/recipes/runnable` or `examples/nrunner/recipes/runnables`


One other issue that this opens is what to present on an `avocado list` command.  What I mean is that, until now, it was presenting the "only" information available, that is, the URI.  Example:

```
avocado list examples/nrunner/recipes/runnable/exec_test_sleep_3.json 
exec-test /bin/sleep
```

Now, with a change such as:

```diff
diff --git a/examples/nrunner/recipes/runnable/exec_test_sleep_3.json b/examples/nrunner/recipes/runnable/exec_test_sleep_3.json
index 23113758b..8e4284eb0 100644
--- a/examples/nrunner/recipes/runnable/exec_test_sleep_3.json
+++ b/examples/nrunner/recipes/runnable/exec_test_sleep_3.json
@@ -1 +1 @@
-{"kind": "exec-test", "uri": "/bin/sleep", "args": ["3"]}
+{"kind": "exec-test", "uri": "/bin/sleep", "args": ["3"], "identifier": "sleep-3-seconds"}
```

It may make sense to show, instead:

```
avocado list examples/nrunner/recipes/runnable/exec_test_sleep_3.json 
exec-test sleep-3-seconds
```

2024-08-02 08:47 UTC, richtja commented
Hi @clebergnu, thanks for your review. I agree with you, and I will update the examples. Also, it reminded to me that I should update our documentation as well.

2024-08-05 12:23 UTC, richtja commented
Hi @clebergnu, I have added the examples and update the `avocado list`. Please have a look.

2024-08-07 17:14 UTC, clebergnu requested changes
Hi @richtja,

I've spotted two things for you to address.  Thanks for this version!

2024-08-07 17:14 UTC, clebergnu commented on avocado/schemas/runnable-recipe.schema.json
> +            "description": "ID of runnable which will be used for indetification during the runtime and in logs. If this is not specified it will be autogenerated based on `runner.identifier_format`
typo: s/indetification/identification/

2024-08-07 17:14 UTC, clebergnu commented on examples/nrunner/recipes/runnable/identifier.json
> +{"kind": "noop", "identifier": "1-test-noop"}
I think having the example identifier here starting with "1-" makes it easy to confuse that with a [Test ID](https://avocado-framework.readthedocs.io/en/latest/guides/user/chapters/concepts.html#test-id)'s first component.

2024-08-12 11:54 UTC, richtja commented
Hi @clebergnu, thanks for your review. I have addressed your comments via force-push. Please have a look.

2024-08-12 15:55 UTC, richtja commented
Hi @clebergnu, I have just updated the `examples/jobs/custom_exec_test.py`. Please have a look.

2024-08-12 16:01 UTC, clebergnu approved these changes
LGTM, thanks!

2024-08-12 16:11 UTC, merged