utils/cpu: Add support for Power11 architecture
avocado-framework/avocado pull request #5993
Opened 2024-08-02 13:04 UTC by disgoel

This commit enhances the CPU utility to support the Power11 architecture by making pattern matching case-insensitive.

2024-08-12 15:23 UTC, clebergnu requested changes
Hi @disgoel, thanks for your work here, but it looks like the change you're proposing is introducing regressions.  Please take a look at the failed checks on the CI.

2025-01-31 07:10 UTC, PraveenPenguin commented
@clebergnu can you please review/unblock this PR as this needed urgently to have some misc test use case

2025-02-10 14:53 UTC, PraveenPenguin commented
@clebergnu @richtja can you please unblock us

2025-02-11 13:13 UTC, richtja approved these changes
LGTM

2025-02-11 13:13 UTC, merged