logging.warn() refactoring for 92lts
avocado-framework/avocado pull request #6000
Opened 2024-08-14 11:06 UTC by richtja

The `logging.warn()` has been deprecated in python3.3, and it will be removed in python3.13. Let's use `logging.warning()` instead in avocado code.

Reference: https://docs.python.org/3.13/whatsnew/3.13.html
This is a fix for https://bugzilla.redhat.com/show_bug.cgi?id=2250847 and https://bugzilla.redhat.com/show_bug.cgi?id=2304322

2024-08-14 14:26 UTC, clebergnu commented on selftests/.data/test_statuses.py
> +        self.log.warning('')
Ditto for the cases in this file too (fix on master first).

2024-08-14 14:29 UTC, clebergnu requested changes
Hi @richtja, the changes here look good, but it would be nice to have them in master first, and then referenced here as a backport.

2024-08-14 14:34 UTC, richtja commented
> Hi @richtja, the changes here look good, but it would be nice to have them in master first, and then referenced here as a backport.

Hi @clebergnu sure I can do that. Actually, those which you pointed out can be even omitted here, because those are only examples and documentation and doesn't cause real troubles in 92lts. What do you think?

2024-08-15 10:34 UTC, clebergnu commented
> > Hi @richtja, the changes here look good, but it would be nice to have them in master first, and then referenced here as a backport.
> 
> Hi @clebergnu sure I can do that. Actually, those which you pointed out can be even omitted here, because those are only examples and documentation and doesn't cause real troubles in 92lts. What do you think?

Oh, you decided to remove them.  Now let's look at the CI issues to get this merged.

2024-08-15 11:50 UTC, clebergnu approved these changes
LGTM, thanks!

2024-08-15 11:55 UTC, merged