Add Path Validation and Environment Loading to TreeNode Class
avocado-framework/avocado pull request #6064
Opened 2024-11-04 11:26 UTC by qisijia367

This pull request introduces path validation and environment loading functionality to the TreeNode class. The changes ensure that the path provided during initialization is valid and that environment variables can be correctly loaded into the node's environment.

2024-11-06 10:27 UTC, richtja requested changes
Hi @qisijia367, thank you very much for these changes, contributions are always welcome. Unfortunately, your patch changes `TreeNode` behaviour because it doesn't count with corner case where the path is only the root path `/` which is valid.  

Can you please update your patch to respect the root path? Also, can you please add test which will tests the behaviour of `TreeNodeEnvOnly` with path ending with `/`?Thank you.

2024-11-07 09:08 UTC, qisijia367 commented
Hi @richtja,Thank you for your suggestions, I have optimized the code again and added some test cases in selftests/unit/tree.py. Please check if they meet the requirements.
![截图_选择区域_20241107170739](https://github.com/user-attachments/assets/6415cd42-5d68-4c65-9d69-e71026512a51)

2024-11-27 09:21 UTC, richtja commented
Hi @qisijia367, the CI is failing after your changes, can you please look into that? Thank you. And If you need any help, just let me know.

2025-10-07 14:39 UTC, clebergnu commented
@qisijia367 if you intend to send a version with CI passing, please reopen this PR.  Thanks!

2025-10-07 14:39 UTC, closed without merging