selftests: drop job-api test variant that may exceed sqlite3's own limits
avocado-framework/avocado pull request #6074
Opened 2024-11-27 00:49 UTC by clebergnu

The sqlite3 module (and actually, even the non-python binary with the same name), have "interesting" limitations when it comes to the database path.
    
When the test that creates the journal file, and checks for it, runs as part of an RPM build, the extra directories (/buildir/...) exceed the path size limit.
    
While it would be possible to check if the "logdir" path, plus the name of the journal database path, would eventually exceed the sqlite3 limits, this logic would be exclusive for one test variant.
    
IMO it does not justify adding such logic to keep a test that has considerably low value.

2024-11-27 09:11 UTC, richtja commented
Hi @clebergnu, can you please add a reference to the failure? I wasn't able to find any CI failure which would be caused by sqlite3 limitations. Thank you.

2024-11-27 15:01 UTC, clebergnu commented
/packit copr-build

2024-11-28 01:09 UTC, clebergnu commented
This is one example of the limitation causing a failure during an RPM build:

```
[stdlog] 2024-11-27 20:07:04,543 avocado.core.status.repo repo             L0065 DEBUG| Task "1-examples/tests/true" started message: "{'status': 'started', 'time': 45051.478570847, 'output_dir': '/builddir/avocado/job-results/job-2024-11-27T20.03-b45e70e/test-results/job-api-5-10-_builddir_build_BUILD_python-avocado-108.0-build_avocado-4e86b09ab23531f034c837829b5ac683bfd97213_selftests_check.py_JobAPIFeaturesTest.test_check_file_exists_run.journal.enabled-True/tmp_dir1s_4y4jb/1-_builddir_build_BUILD_python-avocado-108.0-build_avocado-4e86b09ab23531f034c837829b5ac683bfd97213_selftests_check.py_JobAPIFeaturesTest.test_check_file_exists_run.journal.enabled-True/job-2024-11-27T20.07-7f64ff1/test-results/1-examples_tests_true', 'id': '1-examples/tests/true'}"
[stdlog] 2024-11-27 20:07:04,551 avocado.app human            L0089 DEBUG|  (1/1) examples/tests/true: STARTED
[stdlog] 2024-11-27 20:07:04,552 avocado.app extension_manage L0223 ERROR| Error running method "start_test" of plugin "journal": unable to open database file
[stdlog] 2024-11-27 20:07:04,552 avocado.app stacktrace       L0041 ERROR| 
[stdlog] 2024-11-27 20:07:04,552 avocado.app stacktrace       L0043 ERROR| Reproduced traceback from: /builddir/build/BUILD/python-avocado-108.0-build/BUILDROOT/usr/lib/python3.13/site-packages/avocado/core/extension_manager.py:229
[stdlog] 2024-11-27 20:07:04,554 avocado.app stacktrace       L0050 ERROR| Traceback (most recent call last):
[stdlog] 2024-11-27 20:07:04,554 avocado.app stacktrace       L0050 ERROR|   File "/builddir/build/BUILD/python-avocado-108.0-build/BUILDROOT/usr/lib/python3.13/site-packages/avocado/plugins/journal.py", line 118, in start_test
[stdlog] 2024-11-27 20:07:04,554 avocado.app stacktrace       L0050 ERROR|     self.lazy_init_journal(state)
[stdlog] 2024-11-27 20:07:04,554 avocado.app stacktrace       L0050 ERROR|     ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^
[stdlog] 2024-11-27 20:07:04,554 avocado.app stacktrace       L0050 ERROR|   File "/builddir/build/BUILD/python-avocado-108.0-build/BUILDROOT/usr/lib/python3.13/site-packages/avocado/plugins/journal.py", line 77, in lazy_init_journal
[stdlog] 2024-11-27 20:07:04,554 avocado.app stacktrace       L0050 ERROR|     self._init_journal(state["job_logdir"])
[stdlog] 2024-11-27 20:07:04,554 avocado.app stacktrace       L0050 ERROR|     ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^
[stdlog] 2024-11-27 20:07:04,555 avocado.app stacktrace       L0050 ERROR|   File "/builddir/build/BUILD/python-avocado-108.0-build/BUILDROOT/usr/lib/python3.13/site-packages/avocado/plugins/journal.py", line 66, in _init_journal
[stdlog] 2024-11-27 20:07:04,555 avocado.app stacktrace       L0050 ERROR|     self.journal = sqlite3.connect(self.journal_path)
[stdlog] 2024-11-27 20:07:04,555 avocado.app stacktrace       L0050 ERROR|                    ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
[stdlog] 2024-11-27 20:07:04,555 avocado.app stacktrace       L0050 ERROR| sqlite3.OperationalError: unable to open database file
[stdlog] 2024-11-27 20:07:04,555 avocado.app stacktrace       L0051 ERROR| 
```

2024-11-28 09:52 UTC, richtja requested changes
Hi @clebergnu, thank you for provided example, the previous changes LGTM. But I think that the last commit b80f298cd4bef4c93e367af630b4660ccce504a2 is not related to this PR, am I right?

2024-12-02 12:07 UTC, clebergnu commented
> Hi @clebergnu, thank you for provided example, the previous changes LGTM. But I think that the last commit [b80f298](https://github.com/avocado-framework/avocado/commit/b80f298cd4bef4c93e367af630b4660ccce504a2) is not related to this PR, am I right?

It's not... but it was necessary to include it to prove that the CI can be fixed by this (inclusive).  I can send them in separate PRs, but, I would advise against it because we'd still have CI failures on both cases.

2024-12-02 12:23 UTC, merged