Tags Filtering Fix
avocado-framework/avocado pull request #6083
Opened 2024-12-13 16:19 UTC by harvey0100

Filtering now properly handles both verbose and non-verbose output modes while checking for tag matches.
without changing the existing behavior that users expect when using 'avocado list -t <tag>'

Reference:      https://github.com/avocado-framework/avocado/issues/6066

2024-12-18 12:12 UTC, clebergnu requested changes
Hi @harvey0100, thanks for this!  While it fixes the issue, I believe having the exact behavior of the filtering reused is a must.

Also, adding test coverage so that this doesn't happen again is appreciated.  Something as simple as this:

```diff
diff --git a/selftests/functional/list.py b/selftests/functional/list.py
index 2be6213e3..71f0b1354 100644
--- a/selftests/functional/list.py
+++ b/selftests/functional/list.py
@@ -153,6 +153,23 @@ class ListTestFunctional(TestCaseTmpDir):
             (f"Avocado did not return rc " f"{exit_codes.AVOCADO_ALL_OK}:\n{result}"),
         )
         stdout_lines = result.stdout_text.splitlines()
+        self.assertRegex(
+            stdout_lines[1],
+            r"avocado-instrumented\s.*examples/tests/cit_parameters.py:CitParameters.test\s.*examples/tests/cit_parameters.py:CitParameters.test\savocado-instrumented\sfast",
+        )
+        self.assertRegex(
+            stdout_lines[2],
+            r"avocado-instrumented\s.*examples/tests/passtest.py:PassTest.test\s.*examples/tests/passtest.py:PassTest.test\s.*avocado-instrumented\sfast",
+        )
+        self.assertRegex(
+            stdout_lines[3],
+            r"avocado-instrumented\s.*examples/tests/tags.py:FastTest.test_fast\s.*examples/tests/tags.py:FastTest.test_fast\s.*avocado-instrumented\snet,fast",
+        )
+        self.assertRegex(
+            stdout_lines[4],
+            r"avocado-instrumented\s.*examples/tests/tags.py:FastTest.test_fast_other\s.*examples/tests/tags.py:FastTest.test_fast_other\s.*avocado-instrumented\snet,fast",
+        )
+        self.assertEqual("", stdout_lines[5])
         self.assertIn("TEST TYPES SUMMARY", stdout_lines)
         self.assertIn("avocado-instrumented: 4", stdout_lines)
         self.assertIn("TEST TAGS SUMMARY", stdout_lines)
```

Should do the trick.

Thanks!

2024-12-18 12:12 UTC, clebergnu commented on avocado/plugins/list.py
> +    def _matches_tag_filter(runnable, filter_by_tags):
The filtering itself is a bit more complex, but there's a function you can reuse in `avocado/core/tags.py`.  You could use it like:

```diff
diff --git a/avocado/plugins/list.py b/avocado/plugins/list.py
index 2cf67e26d..156c2ed48 100644
--- a/avocado/plugins/list.py
+++ b/avocado/plugins/list.py
@@ -22,6 +22,7 @@ from avocado.core.plugin_interfaces import CLICmd
 from avocado.core.resolver import ReferenceResolutionResult
 from avocado.core.settings import settings
 from avocado.core.suite import TestSuite
+from avocado.core.tags import filter_tags_on_runnables
 from avocado.utils.astring import iter_tabular_output
 
 
@@ -142,8 +143,18 @@ class List(CLICmd):
         """
         test_matrix = []
         verbose = suite.config.get("core.verbose")
+        tags = suite.config.get("filter.by_tags.tags")
+        include_empty = suite.config.get("filter.by_tags.include_empty")
+        include_empty_key = suite.config.get("filter.by_tags.include_empty_key")
+
         for resolution in suite.resolutions:
-            for runnable in resolution.resolutions:
+            if tags:
+                runnables = filter_tags_on_runnables(
+                    [resolution], tags, include_empty, include_empty_key
+                )
+            else:
+                runnables = resolution.resolutions
+            for runnable in runnables:
                 if verbose:
                     tags = runnable.tags or {}
                     test_matrix.append(
```

2024-12-19 12:30 UTC, harvey0100 commented
Hi @clebergnu 

Thanks for your comments, in complete agreement I've made the changes as requested :)

2024-12-19 14:36 UTC, clebergnu approved these changes
LGTM, thanks!

2024-12-19 14:38 UTC, merged